// Code generated by `gogenitor`. DO NOT EDIT.
package sumup

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"strconv"
)

// SchemasAttachmentGet: File metadata
type SchemasAttachmentGet struct {
	// The ID of the attachment
	Id *string `json:"_id,omitempty"`
	// Whether the file should be processed as an e-invoice
	// Default: false
	EInvoice *bool `json:"e_invoice,omitempty"`
	// The ID of the expense this attachment is related to
	ExpenseId *string `json:"expense_id,omitempty"`
	// Default: map[source_type:manual]
	Metadata *SchemasAttachmentGetMetadata `json:"metadata,omitempty"`
	MimeType *interface{}                  `json:"mime_type,omitempty"`
	// The name of the file
	// Max length: 255
	Name *string `json:"name,omitempty"`
	// Whether the file should be processed by OCR
	// Default: false
	Ocr *bool `json:"ocr,omitempty"`
	// The status of the processing, if applicable
	ProcessingStatus *SchemasAttachmentGetProcessingStatus `json:"processing_status,omitempty"`
	// The size of the file in bytes
	Size *int `json:"size,omitempty"`
}

// SchemasAttachmentGetMetadata is a schema definition.
// Default: map[source_type:manual]
type SchemasAttachmentGetMetadata struct {
	// The source reference of the attachment
	// Max length: 255
	SourceReference *string `json:"source_reference,omitempty"`
	// Default: manual
	SourceType *interface{} `json:"source_type,omitempty"`
}

// SchemasAttachmentGetProcessingStatus: The status of the processing, if applicable
type SchemasAttachmentGetProcessingStatus string

const (
	SchemasAttachmentGetProcessingStatusError   SchemasAttachmentGetProcessingStatus = "error"
	SchemasAttachmentGetProcessingStatusPending SchemasAttachmentGetProcessingStatus = "pending"
	SchemasAttachmentGetProcessingStatusSuccess SchemasAttachmentGetProcessingStatus = "success"
)

// SchemasAttachmentGetWithUrl: File metadata
type SchemasAttachmentGetWithUrl struct {
	// The ID of the attachment
	Id *string `json:"_id,omitempty"`
	// Whether the file should be processed as an e-invoice
	// Default: false
	EInvoice *bool `json:"e_invoice,omitempty"`
	// The ID of the expense this attachment is related to
	ExpenseId *string `json:"expense_id,omitempty"`
	// Default: map[source_type:manual]
	Metadata *SchemasAttachmentGetWithUrlMetadata `json:"metadata,omitempty"`
	MimeType *interface{}                         `json:"mime_type,omitempty"`
	// The name of the file
	// Max length: 255
	Name *string `json:"name,omitempty"`
	// Whether the file should be processed by OCR
	// Default: false
	Ocr *bool `json:"ocr,omitempty"`
	// The status of the processing, if applicable
	ProcessingStatus *SchemasAttachmentGetWithUrlProcessingStatus `json:"processing_status,omitempty"`
	// A public URL to download the file, which expires after 1 hour
	PublicUrl *string `json:"public_url,omitempty"`
	// The size of the file in bytes
	Size *int `json:"size,omitempty"`
}

// SchemasAttachmentGetWithUrlMetadata is a schema definition.
// Default: map[source_type:manual]
type SchemasAttachmentGetWithUrlMetadata struct {
	// The source reference of the attachment
	// Max length: 255
	SourceReference *string `json:"source_reference,omitempty"`
	// Default: manual
	SourceType *interface{} `json:"source_type,omitempty"`
}

// SchemasAttachmentGetWithUrlProcessingStatus: The status of the processing, if applicable
type SchemasAttachmentGetWithUrlProcessingStatus string

const (
	SchemasAttachmentGetWithUrlProcessingStatusError   SchemasAttachmentGetWithUrlProcessingStatus = "error"
	SchemasAttachmentGetWithUrlProcessingStatusPending SchemasAttachmentGetWithUrlProcessingStatus = "pending"
	SchemasAttachmentGetWithUrlProcessingStatusSuccess SchemasAttachmentGetWithUrlProcessingStatus = "success"
)

// ListAllAttachmentsParams: query parameters for listAllAttachments
type ListAllAttachmentsParams struct {
	ExpenseId        *string
	FromCreatedDate  *Date
	IncludePublicUrl *bool
	Limit            *int
	Linked           *bool
	Offset           *int
	Order            *[]string
	Search           *string
	ToCreatedDate    *Date
}

// QueryValues converts [ListAllAttachmentsParams] into [url.Values].
func (p *ListAllAttachmentsParams) QueryValues() url.Values {
	q := make(url.Values)

	if p.ExpenseId != nil {
		q.Set("expense_id", *p.ExpenseId)
	}

	if p.FromCreatedDate != nil {
		q.Set("from_created_date", p.FromCreatedDate.String())
	}

	if p.IncludePublicUrl != nil {
		q.Set("include_public_url", strconv.FormatBool(*p.IncludePublicUrl))
	}

	if p.Limit != nil {
		q.Set("limit", strconv.Itoa(*p.Limit))
	}

	if p.Linked != nil {
		q.Set("linked", strconv.FormatBool(*p.Linked))
	}

	if p.Offset != nil {
		q.Set("offset", strconv.Itoa(*p.Offset))
	}

	if p.Order != nil {
		for _, v := range *p.Order {
			q.Add("order", v)
		}
	}

	if p.Search != nil {
		q.Set("search", *p.Search)
	}

	if p.ToCreatedDate != nil {
		q.Set("to_created_date", p.ToCreatedDate.String())
	}

	return q
}

// UploadAttachmentParams: query parameters for uploadAttachment
type UploadAttachmentParams struct {
	// Whether to wait for the OCR to complete
	Await         *bool
	ContentLength int
}

// QueryValues converts [UploadAttachmentParams] into [url.Values].
func (p *UploadAttachmentParams) QueryValues() url.Values {
	q := make(url.Values)

	if p.Await != nil {
		q.Set("await", strconv.FormatBool(*p.Await))
	}

	q.Set("content-length", strconv.Itoa(p.ContentLength))

	return q
}

// GetAttachmentsByProcessingStatusParams: query parameters for getAttachmentsByProcessingStatus
type GetAttachmentsByProcessingStatusParams struct {
	Limit  *int
	Offset *int
}

// QueryValues converts [GetAttachmentsByProcessingStatusParams] into [url.Values].
func (p *GetAttachmentsByProcessingStatusParams) QueryValues() url.Values {
	q := make(url.Values)

	if p.Limit != nil {
		q.Set("limit", strconv.Itoa(*p.Limit))
	}

	if p.Offset != nil {
		q.Set("offset", strconv.Itoa(*p.Offset))
	}

	return q
}

// ListAllAttachments200Response is a schema definition.
type ListAllAttachments200Response struct {
	Data       *[]SchemasAttachmentGetWithUrl `json:"data,omitempty"`
	Pagination *SchemasPaginationResponse     `json:"pagination,omitempty"`
}

var _ error = (*ListAllAttachments4XXResponse)(nil)

// ListAllAttachments4XXResponse: Request validation error
type ListAllAttachments4XXResponse struct {
	Code       *string `json:"code,omitempty"`
	Error      *string `json:"error,omitempty"`
	Message    *string `json:"message,omitempty"`
	StatusCode *int    `json:"status_code,omitempty"`
}

func (e *ListAllAttachments4XXResponse) Error() string {
	return fmt.Sprintf("code=%v, error=%v, message=%v, statusCode=%v", e.Code, e.Error, e.Message, e.StatusCode)
}

var _ error = (*ListAllAttachments5XXResponse)(nil)

// ListAllAttachments5XXResponse: Internal server error
type ListAllAttachments5XXResponse struct {
	Code       *string `json:"code,omitempty"`
	Error      *string `json:"error,omitempty"`
	Message    *string `json:"message,omitempty"`
	StatusCode *int    `json:"status_code,omitempty"`
}

func (e *ListAllAttachments5XXResponse) Error() string {
	return fmt.Sprintf("code=%v, error=%v, message=%v, statusCode=%v", e.Code, e.Error, e.Message, e.StatusCode)
}

var _ error = (*UploadAttachment4XXResponse)(nil)

// UploadAttachment4XXResponse: Request validation error
type UploadAttachment4XXResponse struct {
	Code       *string `json:"code,omitempty"`
	Error      *string `json:"error,omitempty"`
	Message    *string `json:"message,omitempty"`
	StatusCode *int    `json:"status_code,omitempty"`
}

func (e *UploadAttachment4XXResponse) Error() string {
	return fmt.Sprintf("code=%v, error=%v, message=%v, statusCode=%v", e.Code, e.Error, e.Message, e.StatusCode)
}

var _ error = (*UploadAttachment5XXResponse)(nil)

// UploadAttachment5XXResponse: Internal server error
type UploadAttachment5XXResponse struct {
	Code       *string `json:"code,omitempty"`
	Error      *string `json:"error,omitempty"`
	Message    *string `json:"message,omitempty"`
	StatusCode *int    `json:"status_code,omitempty"`
}

func (e *UploadAttachment5XXResponse) Error() string {
	return fmt.Sprintf("code=%v, error=%v, message=%v, statusCode=%v", e.Code, e.Error, e.Message, e.StatusCode)
}

var _ error = (*DeleteAttachment4XXResponse)(nil)

// DeleteAttachment4XXResponse: Request validation error
type DeleteAttachment4XXResponse struct {
	Code       *string `json:"code,omitempty"`
	Error      *string `json:"error,omitempty"`
	Message    *string `json:"message,omitempty"`
	StatusCode *int    `json:"status_code,omitempty"`
}

func (e *DeleteAttachment4XXResponse) Error() string {
	return fmt.Sprintf("code=%v, error=%v, message=%v, statusCode=%v", e.Code, e.Error, e.Message, e.StatusCode)
}

var _ error = (*DeleteAttachment5XXResponse)(nil)

// DeleteAttachment5XXResponse: Internal server error
type DeleteAttachment5XXResponse struct {
	Code       *string `json:"code,omitempty"`
	Error      *string `json:"error,omitempty"`
	Message    *string `json:"message,omitempty"`
	StatusCode *int    `json:"status_code,omitempty"`
}

func (e *DeleteAttachment5XXResponse) Error() string {
	return fmt.Sprintf("code=%v, error=%v, message=%v, statusCode=%v", e.Code, e.Error, e.Message, e.StatusCode)
}

var _ error = (*GetAttachment4XXResponse)(nil)

// GetAttachment4XXResponse: Request validation error
type GetAttachment4XXResponse struct {
	Code       *string `json:"code,omitempty"`
	Error      *string `json:"error,omitempty"`
	Message    *string `json:"message,omitempty"`
	StatusCode *int    `json:"status_code,omitempty"`
}

func (e *GetAttachment4XXResponse) Error() string {
	return fmt.Sprintf("code=%v, error=%v, message=%v, statusCode=%v", e.Code, e.Error, e.Message, e.StatusCode)
}

var _ error = (*GetAttachment5XXResponse)(nil)

// GetAttachment5XXResponse: Internal server error
type GetAttachment5XXResponse struct {
	Code       *string `json:"code,omitempty"`
	Error      *string `json:"error,omitempty"`
	Message    *string `json:"message,omitempty"`
	StatusCode *int    `json:"status_code,omitempty"`
}

func (e *GetAttachment5XXResponse) Error() string {
	return fmt.Sprintf("code=%v, error=%v, message=%v, statusCode=%v", e.Code, e.Error, e.Message, e.StatusCode)
}

// GetAttachmentsByProcessingStatus200Response is a schema definition.
type GetAttachmentsByProcessingStatus200Response struct {
	Data       *[]SchemasAttachmentGet    `json:"data,omitempty"`
	Pagination *SchemasPaginationResponse `json:"pagination,omitempty"`
}

var _ error = (*GetAttachmentsByProcessingStatus4XXResponse)(nil)

// GetAttachmentsByProcessingStatus4XXResponse: Request validation error
type GetAttachmentsByProcessingStatus4XXResponse struct {
	Code       *string `json:"code,omitempty"`
	Error      *string `json:"error,omitempty"`
	Message    *string `json:"message,omitempty"`
	StatusCode *int    `json:"status_code,omitempty"`
}

func (e *GetAttachmentsByProcessingStatus4XXResponse) Error() string {
	return fmt.Sprintf("code=%v, error=%v, message=%v, statusCode=%v", e.Code, e.Error, e.Message, e.StatusCode)
}

var _ error = (*GetAttachmentsByProcessingStatus5XXResponse)(nil)

// GetAttachmentsByProcessingStatus5XXResponse: Internal server error
type GetAttachmentsByProcessingStatus5XXResponse struct {
	Code       *string `json:"code,omitempty"`
	Error      *string `json:"error,omitempty"`
	Message    *string `json:"message,omitempty"`
	StatusCode *int    `json:"status_code,omitempty"`
}

func (e *GetAttachmentsByProcessingStatus5XXResponse) Error() string {
	return fmt.Sprintf("code=%v, error=%v, message=%v, statusCode=%v", e.Code, e.Error, e.Message, e.StatusCode)
}

type AttachmentsService service

// ListAllAttachments: List all attachments with pagination and optionally free-text search
func (s *AttachmentsService) ListAllAttachments(ctx context.Context, merchantCode string, params ListAllAttachmentsParams) (*ListAllAttachments200Response, error) {
	path := fmt.Sprintf("/merchants/%v/expenses-attachments", merchantCode)

	req, err := s.client.NewRequest(ctx, http.MethodGet, path, http.NoBody)
	if err != nil {
		return nil, fmt.Errorf("error building request: %v", err)
	}
	req.URL.RawQuery = params.QueryValues().Encode()

	resp, err := s.client.Do(req)
	if err != nil {
		return nil, fmt.Errorf("error sending request: %v", err)
	}
	defer resp.Body.Close()

	switch resp.StatusCode {
	case http.StatusOK:
		var v ListAllAttachments200Response
		if err := json.NewDecoder(resp.Body).Decode(&v); err != nil {
			return nil, fmt.Errorf("decode response: %s", err.Error())
		}

		return &v, nil
	case http.StatusBadRequest:
		var apiErr ListAllAttachments4XXResponse
		if err := json.NewDecoder(resp.Body).Decode(&apiErr); err != nil {
			return nil, fmt.Errorf("read error response: %s", err.Error())
		}

		return nil, &apiErr
	case http.StatusInternalServerError:
		var apiErr ListAllAttachments5XXResponse
		if err := json.NewDecoder(resp.Body).Decode(&apiErr); err != nil {
			return nil, fmt.Errorf("read error response: %s", err.Error())
		}

		return nil, &apiErr
	default:
		return nil, fmt.Errorf("unexpected response %d: %s", resp.StatusCode, http.StatusText(resp.StatusCode))
	}
}

// UploadAttachment: Upload a single attachment
func (s *AttachmentsService) UploadAttachment(ctx context.Context, merchantCode string, params UploadAttachmentParams) (*SchemasAttachmentGetWithUrl, error) {
	buf := new(bytes.Buffer)
	if err := json.NewEncoder(buf).Encode(body); err != nil {
		return nil, fmt.Errorf("encoding json body request failed: %v", err)
	}

	path := fmt.Sprintf("/merchants/%v/expenses-attachments", merchantCode)

	req, err := s.client.NewRequest(ctx, http.MethodPost, path, buf)
	if err != nil {
		return nil, fmt.Errorf("error building request: %v", err)
	}
	req.URL.RawQuery = params.QueryValues().Encode()

	resp, err := s.client.Do(req)
	if err != nil {
		return nil, fmt.Errorf("error sending request: %v", err)
	}
	defer resp.Body.Close()

	switch resp.StatusCode {
	case http.StatusOK:
		var v SchemasAttachmentGetWithUrl
		if err := json.NewDecoder(resp.Body).Decode(&v); err != nil {
			return nil, fmt.Errorf("decode response: %s", err.Error())
		}

		return &v, nil
	case http.StatusBadRequest:
		var apiErr UploadAttachment4XXResponse
		if err := json.NewDecoder(resp.Body).Decode(&apiErr); err != nil {
			return nil, fmt.Errorf("read error response: %s", err.Error())
		}

		return nil, &apiErr
	case http.StatusInternalServerError:
		var apiErr UploadAttachment5XXResponse
		if err := json.NewDecoder(resp.Body).Decode(&apiErr); err != nil {
			return nil, fmt.Errorf("read error response: %s", err.Error())
		}

		return nil, &apiErr
	default:
		return nil, fmt.Errorf("unexpected response %d: %s", resp.StatusCode, http.StatusText(resp.StatusCode))
	}
}

// DeleteAttachment: Delete a given attachment
func (s *AttachmentsService) DeleteAttachment(ctx context.Context, merchantCode string, id string) (*SchemasDeleteResponse, error) {
	path := fmt.Sprintf("/merchants/%v/expenses-attachments/%v", merchantCode, id)

	req, err := s.client.NewRequest(ctx, http.MethodDelete, path, http.NoBody)
	if err != nil {
		return nil, fmt.Errorf("error building request: %v", err)
	}

	resp, err := s.client.Do(req)
	if err != nil {
		return nil, fmt.Errorf("error sending request: %v", err)
	}
	defer resp.Body.Close()

	switch resp.StatusCode {
	case http.StatusOK:
		var v SchemasDeleteResponse
		if err := json.NewDecoder(resp.Body).Decode(&v); err != nil {
			return nil, fmt.Errorf("decode response: %s", err.Error())
		}

		return &v, nil
	case http.StatusBadRequest:
		var apiErr DeleteAttachment4XXResponse
		if err := json.NewDecoder(resp.Body).Decode(&apiErr); err != nil {
			return nil, fmt.Errorf("read error response: %s", err.Error())
		}

		return nil, &apiErr
	case http.StatusInternalServerError:
		var apiErr DeleteAttachment5XXResponse
		if err := json.NewDecoder(resp.Body).Decode(&apiErr); err != nil {
			return nil, fmt.Errorf("read error response: %s", err.Error())
		}

		return nil, &apiErr
	default:
		return nil, fmt.Errorf("unexpected response %d: %s", resp.StatusCode, http.StatusText(resp.StatusCode))
	}
}

// GetAttachment: Download all attachments for a given expense
func (s *AttachmentsService) GetAttachment(ctx context.Context, merchantCode string, id string) (*SchemasAttachmentGetWithUrl, error) {
	path := fmt.Sprintf("/merchants/%v/expenses-attachments/%v", merchantCode, id)

	req, err := s.client.NewRequest(ctx, http.MethodGet, path, http.NoBody)
	if err != nil {
		return nil, fmt.Errorf("error building request: %v", err)
	}

	resp, err := s.client.Do(req)
	if err != nil {
		return nil, fmt.Errorf("error sending request: %v", err)
	}
	defer resp.Body.Close()

	switch resp.StatusCode {
	case http.StatusOK:
		var v SchemasAttachmentGetWithUrl
		if err := json.NewDecoder(resp.Body).Decode(&v); err != nil {
			return nil, fmt.Errorf("decode response: %s", err.Error())
		}

		return &v, nil
	case http.StatusBadRequest:
		var apiErr GetAttachment4XXResponse
		if err := json.NewDecoder(resp.Body).Decode(&apiErr); err != nil {
			return nil, fmt.Errorf("read error response: %s", err.Error())
		}

		return nil, &apiErr
	case http.StatusInternalServerError:
		var apiErr GetAttachment5XXResponse
		if err := json.NewDecoder(resp.Body).Decode(&apiErr); err != nil {
			return nil, fmt.Errorf("read error response: %s", err.Error())
		}

		return nil, &apiErr
	default:
		return nil, fmt.Errorf("unexpected response %d: %s", resp.StatusCode, http.StatusText(resp.StatusCode))
	}
}

// GetAttachmentsByProcessingStatus: List all attachments with a given processing status with pagination
func (s *AttachmentsService) GetAttachmentsByProcessingStatus(ctx context.Context, merchantCode string, status string, params GetAttachmentsByProcessingStatusParams) (*GetAttachmentsByProcessingStatus200Response, error) {
	path := fmt.Sprintf("/merchants/%v/expenses-attachments/processing/status/%v", merchantCode, status)

	req, err := s.client.NewRequest(ctx, http.MethodGet, path, http.NoBody)
	if err != nil {
		return nil, fmt.Errorf("error building request: %v", err)
	}
	req.URL.RawQuery = params.QueryValues().Encode()

	resp, err := s.client.Do(req)
	if err != nil {
		return nil, fmt.Errorf("error sending request: %v", err)
	}
	defer resp.Body.Close()

	switch resp.StatusCode {
	case http.StatusOK:
		var v GetAttachmentsByProcessingStatus200Response
		if err := json.NewDecoder(resp.Body).Decode(&v); err != nil {
			return nil, fmt.Errorf("decode response: %s", err.Error())
		}

		return &v, nil
	case http.StatusBadRequest:
		var apiErr GetAttachmentsByProcessingStatus4XXResponse
		if err := json.NewDecoder(resp.Body).Decode(&apiErr); err != nil {
			return nil, fmt.Errorf("read error response: %s", err.Error())
		}

		return nil, &apiErr
	case http.StatusInternalServerError:
		var apiErr GetAttachmentsByProcessingStatus5XXResponse
		if err := json.NewDecoder(resp.Body).Decode(&apiErr); err != nil {
			return nil, fmt.Errorf("read error response: %s", err.Error())
		}

		return nil, &apiErr
	default:
		return nil, fmt.Errorf("unexpected response %d: %s", resp.StatusCode, http.StatusText(resp.StatusCode))
	}
}
