// Code generated by `gogenitor`. DO NOT EDIT.
package sumup

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"strconv"
)

// SchemasCategoryCreate: Details of the category
type SchemasCategoryCreate struct {
	// Max length: 255
	Description *string `json:"description,omitempty"`
	// Default: false
	Hidden *bool `json:"hidden,omitempty"`
	// Max length: 255
	Name string `json:"name"`
}

// SchemasCategoryGet: Details of the category
type SchemasCategoryGet struct {
	// The ID of the expense
	Id *string `json:"_id,omitempty"`
	// Max length: 255
	Description *string `json:"description,omitempty"`
	// Default: false
	Hidden *bool `json:"hidden,omitempty"`
	// Max length: 255
	Name *string `json:"name,omitempty"`
	// indicates if the category is a default or custom
	Type *SchemasCategoryGetType `json:"type,omitempty"`
}

// SchemasCategoryUpdate: Details of the category
type SchemasCategoryUpdate struct {
	// Max length: 255
	Description *string `json:"description,omitempty"`
	Hidden      *bool   `json:"hidden,omitempty"`
	// Max length: 255
	Name *string `json:"name,omitempty"`
}

// NewCategoryBody: Details of the category
type NewCategoryBody struct {
	// Max length: 255
	Description *string `json:"description,omitempty"`
	// Default: false
	Hidden *bool `json:"hidden,omitempty"`
	// Max length: 255
	Name string `json:"name"`
}

// UpdateCategoryBody: Details of the category
type UpdateCategoryBody struct {
	// Max length: 255
	Description *string `json:"description,omitempty"`
	Hidden      *bool   `json:"hidden,omitempty"`
	// Max length: 255
	Name *string `json:"name,omitempty"`
}

// GetAllCategoriesParams: query parameters for getAllCategories
type GetAllCategoriesParams struct {
	// If true, hidden categories will be included
	Hidden *bool
	Limit  *int
	Offset *int
	Order  *[]string
	Search *string
}

// QueryValues converts [GetAllCategoriesParams] into [url.Values].
func (p *GetAllCategoriesParams) QueryValues() url.Values {
	q := make(url.Values)

	if p.Hidden != nil {
		q.Set("hidden", strconv.FormatBool(*p.Hidden))
	}

	if p.Limit != nil {
		q.Set("limit", strconv.Itoa(*p.Limit))
	}

	if p.Offset != nil {
		q.Set("offset", strconv.Itoa(*p.Offset))
	}

	if p.Order != nil {
		for _, v := range *p.Order {
			q.Add("order", v)
		}
	}

	if p.Search != nil {
		q.Set("search", *p.Search)
	}

	return q
}

// NewCategoryParams: query parameters for newCategory
type NewCategoryParams struct {
	// Return the created category in the response
	Prefer *string
}

// QueryValues converts [NewCategoryParams] into [url.Values].
func (p *NewCategoryParams) QueryValues() url.Values {
	q := make(url.Values)

	if p.Prefer != nil {
		q.Set("prefer", *p.Prefer)
	}

	return q
}

// GetAllCategories200Response is a schema definition.
type GetAllCategories200Response struct {
	Data       *[]SchemasCategoryGet      `json:"data,omitempty"`
	Pagination *SchemasPaginationResponse `json:"pagination,omitempty"`
}

var _ error = (*GetAllCategories4XXResponse)(nil)

// GetAllCategories4XXResponse: Request validation error
type GetAllCategories4XXResponse struct {
	Code       *string `json:"code,omitempty"`
	Error      *string `json:"error,omitempty"`
	Message    *string `json:"message,omitempty"`
	StatusCode *int    `json:"status_code,omitempty"`
}

func (e *GetAllCategories4XXResponse) Error() string {
	return fmt.Sprintf("code=%v, error=%v, message=%v, statusCode=%v", e.Code, e.Error, e.Message, e.StatusCode)
}

var _ error = (*GetAllCategories5XXResponse)(nil)

// GetAllCategories5XXResponse: Internal server error
type GetAllCategories5XXResponse struct {
	Code       *string `json:"code,omitempty"`
	Error      *string `json:"error,omitempty"`
	Message    *string `json:"message,omitempty"`
	StatusCode *int    `json:"status_code,omitempty"`
}

func (e *GetAllCategories5XXResponse) Error() string {
	return fmt.Sprintf("code=%v, error=%v, message=%v, statusCode=%v", e.Code, e.Error, e.Message, e.StatusCode)
}

var _ error = (*NewCategory4XXResponse)(nil)

// NewCategory4XXResponse: Request validation error
type NewCategory4XXResponse struct {
	Code       *string `json:"code,omitempty"`
	Error      *string `json:"error,omitempty"`
	Message    *string `json:"message,omitempty"`
	StatusCode *int    `json:"status_code,omitempty"`
}

func (e *NewCategory4XXResponse) Error() string {
	return fmt.Sprintf("code=%v, error=%v, message=%v, statusCode=%v", e.Code, e.Error, e.Message, e.StatusCode)
}

var _ error = (*NewCategory5XXResponse)(nil)

// NewCategory5XXResponse: Internal server error
type NewCategory5XXResponse struct {
	Code       *string `json:"code,omitempty"`
	Error      *string `json:"error,omitempty"`
	Message    *string `json:"message,omitempty"`
	StatusCode *int    `json:"status_code,omitempty"`
}

func (e *NewCategory5XXResponse) Error() string {
	return fmt.Sprintf("code=%v, error=%v, message=%v, statusCode=%v", e.Code, e.Error, e.Message, e.StatusCode)
}

var _ error = (*DeleteCategory4XXResponse)(nil)

// DeleteCategory4XXResponse: Request validation error
type DeleteCategory4XXResponse struct {
	Code       *string `json:"code,omitempty"`
	Error      *string `json:"error,omitempty"`
	Message    *string `json:"message,omitempty"`
	StatusCode *int    `json:"status_code,omitempty"`
}

func (e *DeleteCategory4XXResponse) Error() string {
	return fmt.Sprintf("code=%v, error=%v, message=%v, statusCode=%v", e.Code, e.Error, e.Message, e.StatusCode)
}

var _ error = (*DeleteCategory5XXResponse)(nil)

// DeleteCategory5XXResponse: Internal server error
type DeleteCategory5XXResponse struct {
	Code       *string `json:"code,omitempty"`
	Error      *string `json:"error,omitempty"`
	Message    *string `json:"message,omitempty"`
	StatusCode *int    `json:"status_code,omitempty"`
}

func (e *DeleteCategory5XXResponse) Error() string {
	return fmt.Sprintf("code=%v, error=%v, message=%v, statusCode=%v", e.Code, e.Error, e.Message, e.StatusCode)
}

var _ error = (*GetCategoryById4XXResponse)(nil)

// GetCategoryById4XXResponse: Request validation error
type GetCategoryById4XXResponse struct {
	Code       *string `json:"code,omitempty"`
	Error      *string `json:"error,omitempty"`
	Message    *string `json:"message,omitempty"`
	StatusCode *int    `json:"status_code,omitempty"`
}

func (e *GetCategoryById4XXResponse) Error() string {
	return fmt.Sprintf("code=%v, error=%v, message=%v, statusCode=%v", e.Code, e.Error, e.Message, e.StatusCode)
}

var _ error = (*GetCategoryById5XXResponse)(nil)

// GetCategoryById5XXResponse: Internal server error
type GetCategoryById5XXResponse struct {
	Code       *string `json:"code,omitempty"`
	Error      *string `json:"error,omitempty"`
	Message    *string `json:"message,omitempty"`
	StatusCode *int    `json:"status_code,omitempty"`
}

func (e *GetCategoryById5XXResponse) Error() string {
	return fmt.Sprintf("code=%v, error=%v, message=%v, statusCode=%v", e.Code, e.Error, e.Message, e.StatusCode)
}

var _ error = (*UpdateCategory4XXResponse)(nil)

// UpdateCategory4XXResponse: Request validation error
type UpdateCategory4XXResponse struct {
	Code       *string `json:"code,omitempty"`
	Error      *string `json:"error,omitempty"`
	Message    *string `json:"message,omitempty"`
	StatusCode *int    `json:"status_code,omitempty"`
}

func (e *UpdateCategory4XXResponse) Error() string {
	return fmt.Sprintf("code=%v, error=%v, message=%v, statusCode=%v", e.Code, e.Error, e.Message, e.StatusCode)
}

var _ error = (*UpdateCategory5XXResponse)(nil)

// UpdateCategory5XXResponse: Internal server error
type UpdateCategory5XXResponse struct {
	Code       *string `json:"code,omitempty"`
	Error      *string `json:"error,omitempty"`
	Message    *string `json:"message,omitempty"`
	StatusCode *int    `json:"status_code,omitempty"`
}

func (e *UpdateCategory5XXResponse) Error() string {
	return fmt.Sprintf("code=%v, error=%v, message=%v, statusCode=%v", e.Code, e.Error, e.Message, e.StatusCode)
}

type CategoriesService service

// GetAllCategories: Get all categories (includes default, custom and hidden categories)
func (s *CategoriesService) GetAllCategories(ctx context.Context, merchantCode string, params GetAllCategoriesParams) (*GetAllCategories200Response, error) {
	path := fmt.Sprintf("/merchants/%v/expenses-categories", merchantCode)

	req, err := s.client.NewRequest(ctx, http.MethodGet, path, http.NoBody)
	if err != nil {
		return nil, fmt.Errorf("error building request: %v", err)
	}
	req.URL.RawQuery = params.QueryValues().Encode()

	resp, err := s.client.Do(req)
	if err != nil {
		return nil, fmt.Errorf("error sending request: %v", err)
	}
	defer resp.Body.Close()

	switch resp.StatusCode {
	case http.StatusOK:
		var v GetAllCategories200Response
		if err := json.NewDecoder(resp.Body).Decode(&v); err != nil {
			return nil, fmt.Errorf("decode response: %s", err.Error())
		}

		return &v, nil
	case http.StatusBadRequest:
		var apiErr GetAllCategories4XXResponse
		if err := json.NewDecoder(resp.Body).Decode(&apiErr); err != nil {
			return nil, fmt.Errorf("read error response: %s", err.Error())
		}

		return nil, &apiErr
	case http.StatusInternalServerError:
		var apiErr GetAllCategories5XXResponse
		if err := json.NewDecoder(resp.Body).Decode(&apiErr); err != nil {
			return nil, fmt.Errorf("read error response: %s", err.Error())
		}

		return nil, &apiErr
	default:
		return nil, fmt.Errorf("unexpected response %d: %s", resp.StatusCode, http.StatusText(resp.StatusCode))
	}
}

// NewCategory: Create new custom category
func (s *CategoriesService) NewCategory(ctx context.Context, merchantCode string, body NewCategoryBody, params NewCategoryParams) (*SchemasCreateResponse, error) {
	buf := new(bytes.Buffer)
	if err := json.NewEncoder(buf).Encode(body); err != nil {
		return nil, fmt.Errorf("encoding json body request failed: %v", err)
	}

	path := fmt.Sprintf("/merchants/%v/expenses-categories", merchantCode)

	req, err := s.client.NewRequest(ctx, http.MethodPost, path, buf)
	if err != nil {
		return nil, fmt.Errorf("error building request: %v", err)
	}
	req.URL.RawQuery = params.QueryValues().Encode()

	resp, err := s.client.Do(req)
	if err != nil {
		return nil, fmt.Errorf("error sending request: %v", err)
	}
	defer resp.Body.Close()

	switch resp.StatusCode {
	case http.StatusOK:
		var v SchemasCreateResponse
		if err := json.NewDecoder(resp.Body).Decode(&v); err != nil {
			return nil, fmt.Errorf("decode response: %s", err.Error())
		}

		return &v, nil
	case http.StatusCreated:
		var v SchemasCategoryGet
		if err := json.NewDecoder(resp.Body).Decode(&v); err != nil {
			return nil, fmt.Errorf("decode response: %s", err.Error())
		}

		return &v, nil
	case http.StatusBadRequest:
		var apiErr NewCategory4XXResponse
		if err := json.NewDecoder(resp.Body).Decode(&apiErr); err != nil {
			return nil, fmt.Errorf("read error response: %s", err.Error())
		}

		return nil, &apiErr
	case http.StatusInternalServerError:
		var apiErr NewCategory5XXResponse
		if err := json.NewDecoder(resp.Body).Decode(&apiErr); err != nil {
			return nil, fmt.Errorf("read error response: %s", err.Error())
		}

		return nil, &apiErr
	default:
		return nil, fmt.Errorf("unexpected response %d: %s", resp.StatusCode, http.StatusText(resp.StatusCode))
	}
}

// DeleteCategory: Delete a category (if it was created from a DEFAULT category, the default one will now be
// visible instead)
func (s *CategoriesService) DeleteCategory(ctx context.Context, merchantCode string, id string) (*SchemasDeleteResponse, error) {
	path := fmt.Sprintf("/merchants/%v/expenses-categories/%v", merchantCode, id)

	req, err := s.client.NewRequest(ctx, http.MethodDelete, path, http.NoBody)
	if err != nil {
		return nil, fmt.Errorf("error building request: %v", err)
	}

	resp, err := s.client.Do(req)
	if err != nil {
		return nil, fmt.Errorf("error sending request: %v", err)
	}
	defer resp.Body.Close()

	switch resp.StatusCode {
	case http.StatusOK:
		var v SchemasDeleteResponse
		if err := json.NewDecoder(resp.Body).Decode(&v); err != nil {
			return nil, fmt.Errorf("decode response: %s", err.Error())
		}

		return &v, nil
	case http.StatusBadRequest:
		var apiErr DeleteCategory4XXResponse
		if err := json.NewDecoder(resp.Body).Decode(&apiErr); err != nil {
			return nil, fmt.Errorf("read error response: %s", err.Error())
		}

		return nil, &apiErr
	case http.StatusInternalServerError:
		var apiErr DeleteCategory5XXResponse
		if err := json.NewDecoder(resp.Body).Decode(&apiErr); err != nil {
			return nil, fmt.Errorf("read error response: %s", err.Error())
		}

		return nil, &apiErr
	default:
		return nil, fmt.Errorf("unexpected response %d: %s", resp.StatusCode, http.StatusText(resp.StatusCode))
	}
}

// GetCategoryById: Get a category by its ID
func (s *CategoriesService) GetCategoryById(ctx context.Context, merchantCode string, id string) (*SchemasCategoryGet, error) {
	path := fmt.Sprintf("/merchants/%v/expenses-categories/%v", merchantCode, id)

	req, err := s.client.NewRequest(ctx, http.MethodGet, path, http.NoBody)
	if err != nil {
		return nil, fmt.Errorf("error building request: %v", err)
	}

	resp, err := s.client.Do(req)
	if err != nil {
		return nil, fmt.Errorf("error sending request: %v", err)
	}
	defer resp.Body.Close()

	switch resp.StatusCode {
	case http.StatusOK:
		var v SchemasCategoryGet
		if err := json.NewDecoder(resp.Body).Decode(&v); err != nil {
			return nil, fmt.Errorf("decode response: %s", err.Error())
		}

		return &v, nil
	case http.StatusBadRequest:
		var apiErr GetCategoryById4XXResponse
		if err := json.NewDecoder(resp.Body).Decode(&apiErr); err != nil {
			return nil, fmt.Errorf("read error response: %s", err.Error())
		}

		return nil, &apiErr
	case http.StatusInternalServerError:
		var apiErr GetCategoryById5XXResponse
		if err := json.NewDecoder(resp.Body).Decode(&apiErr); err != nil {
			return nil, fmt.Errorf("read error response: %s", err.Error())
		}

		return nil, &apiErr
	default:
		return nil, fmt.Errorf("unexpected response %d: %s", resp.StatusCode, http.StatusText(resp.StatusCode))
	}
}

// UpdateCategory: Update a category
func (s *CategoriesService) UpdateCategory(ctx context.Context, merchantCode string, id string, body UpdateCategoryBody) (*SchemasUpdateResponse, error) {
	buf := new(bytes.Buffer)
	if err := json.NewEncoder(buf).Encode(body); err != nil {
		return nil, fmt.Errorf("encoding json body request failed: %v", err)
	}

	path := fmt.Sprintf("/merchants/%v/expenses-categories/%v", merchantCode, id)

	req, err := s.client.NewRequest(ctx, http.MethodPatch, path, buf)
	if err != nil {
		return nil, fmt.Errorf("error building request: %v", err)
	}

	resp, err := s.client.Do(req)
	if err != nil {
		return nil, fmt.Errorf("error sending request: %v", err)
	}
	defer resp.Body.Close()

	switch resp.StatusCode {
	case http.StatusOK:
		var v SchemasUpdateResponse
		if err := json.NewDecoder(resp.Body).Decode(&v); err != nil {
			return nil, fmt.Errorf("decode response: %s", err.Error())
		}

		return &v, nil
	case http.StatusBadRequest:
		var apiErr UpdateCategory4XXResponse
		if err := json.NewDecoder(resp.Body).Decode(&apiErr); err != nil {
			return nil, fmt.Errorf("read error response: %s", err.Error())
		}

		return nil, &apiErr
	case http.StatusInternalServerError:
		var apiErr UpdateCategory5XXResponse
		if err := json.NewDecoder(resp.Body).Decode(&apiErr); err != nil {
			return nil, fmt.Errorf("read error response: %s", err.Error())
		}

		return nil, &apiErr
	default:
		return nil, fmt.Errorf("unexpected response %d: %s", resp.StatusCode, http.StatusText(resp.StatusCode))
	}
}
