// Code generated by `go-sdk-gen`. DO NOT EDIT.

package sumup

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"strconv"
	"time"

	"github.com/sumup/sumup-go/client"
	"github.com/sumup/sumup-go/internal/ptr"
	"github.com/sumup/sumup-go/nullable"
)

// __Required when payment type is `card`.__ Details of the payment card.
type Card struct {
	// Three or four-digit card verification value (security code) of the payment card.
	// Write only
	// Min length: 3
	// Max length: 4
	Cvv string `json:"cvv"`
	// Month from the expiration time of the payment card. Accepted format is `MM`.
	// Write only
	ExpiryMonth CardExpiryMonth `json:"expiry_month"`
	// Year from the expiration time of the payment card. Accepted formats are `YY` and `YYYY`.
	// Write only
	// Min length: 2
	// Max length: 4
	ExpiryYear string `json:"expiry_year"`
	// Name of the cardholder as it appears on the payment card.
	// Write only
	Name string `json:"name"`
	// Number of the payment card (without spaces).
	// Write only
	Number string `json:"number"`
	// Issuing card network of the payment card used for the transaction.
	Type CardType `json:"type"`
	// Required five-digit ZIP code. Applicable only to merchant users in the USA.
	// Write only
	// Min length: 5
	// Max length: 5
	ZipCode *string `json:"zip_code,omitempty"`
}

// Month from the expiration time of the payment card. Accepted format is `MM`.
// Write only
type CardExpiryMonth string

const (
	CardExpiryMonth01 CardExpiryMonth = "01"
	CardExpiryMonth02 CardExpiryMonth = "02"
	CardExpiryMonth03 CardExpiryMonth = "03"
	CardExpiryMonth04 CardExpiryMonth = "04"
	CardExpiryMonth05 CardExpiryMonth = "05"
	CardExpiryMonth06 CardExpiryMonth = "06"
	CardExpiryMonth07 CardExpiryMonth = "07"
	CardExpiryMonth08 CardExpiryMonth = "08"
	CardExpiryMonth09 CardExpiryMonth = "09"
	CardExpiryMonth10 CardExpiryMonth = "10"
	CardExpiryMonth11 CardExpiryMonth = "11"
	CardExpiryMonth12 CardExpiryMonth = "12"
)

// Core checkout resource returned by the Checkouts API. A checkout is created before payment processing and
// then updated as payment attempts, redirects, and resulting transactions are attached to it.
type Checkout struct {
	// Amount to be charged to the payer, expressed in major units.
	Amount *float32 `json:"amount,omitempty"`
	// Merchant-defined reference for the checkout. Use it to correlate the SumUp checkout with your own order, cart,
	// subscription, or payment attempt in your systems.
	// Max length: 90
	CheckoutReference *string `json:"checkout_reference,omitempty"`
	// Three-letter [ISO4217](https://en.wikipedia.org/wiki/ISO_4217) code of the currency for the amount. Currently supported
	// currency values are enumerated above.
	Currency *Currency `json:"currency,omitempty"`
	// Merchant-scoped identifier of the customer associated with the checkout. Use it when storing payment instruments
	// or reusing saved customer context for recurring and returning-payer flows.
	CustomerID *string `json:"customer_id,omitempty"`
	// Date and time of the creation of the payment checkout. Response format expressed according to [ISO8601](https://en.wikipedia.org/wiki/ISO_8601) code.
	Date *time.Time `json:"date,omitempty"`
	// Short merchant-defined description shown in SumUp tools and reporting. Use it to make the checkout easier to
	// recognize in dashboards, support workflows, and reconciliation.
	Description *string `json:"description,omitempty"`
	// Unique SumUp identifier of the checkout resource.
	// Read only
	ID *string `json:"id,omitempty"`
	// Details of the mandate linked to the saved payment instrument.
	Mandate *MandateResponse `json:"mandate,omitempty"`
	// Merchant account that receives the payment.
	MerchantCode *string `json:"merchant_code,omitempty"`
	// Optional backend callback URL used by SumUp to notify your platform about processing updates for the checkout.
	//
	// Format: uri
	ReturnURL *string `json:"return_url,omitempty"`
	// Current high-level state of the checkout. `PENDING` means the checkout exists but is not yet completed, `PAID`
	// means a payment succeeded, `FAILED` means the latest processing attempt failed, and `EXPIRED` means the checkout
	// can no longer be processed.
	Status *CheckoutStatus `json:"status,omitempty"`
	// Payment attempts and resulting transaction records linked to this checkout. Use the Transactions endpoints when
	// you need the authoritative payment result and event history.
	// Unique items only
	Transactions []CheckoutTransaction `json:"transactions,omitempty"`
	// Optional expiration timestamp. The checkout must be processed before this moment, otherwise it becomes unusable.
	// If omitted, the checkout does not have an explicit expiry time.
	ValidUntil *nullable.Field[time.Time] `json:"valid_until,omitempty"`
}

// Current high-level state of the checkout. `PENDING` means the checkout exists but is not yet completed, `PAID`
// means a payment succeeded, `FAILED` means the latest processing attempt failed, and `EXPIRED` means the checkout
// can no longer be processed.
type CheckoutStatus string

const (
	CheckoutStatusExpired CheckoutStatus = "EXPIRED"
	CheckoutStatusFailed  CheckoutStatus = "FAILED"
	CheckoutStatusPaid    CheckoutStatus = "PAID"
	CheckoutStatusPending CheckoutStatus = "PENDING"
)

// CheckoutTransaction is a schema definition.
type CheckoutTransaction struct {
	// Total amount of the transaction.
	Amount *float32 `json:"amount,omitempty"`
	// Authorization code for the transaction sent by the payment card issuer or bank. Applicable only to card payments.
	AuthCode *string `json:"auth_code,omitempty"`
	// Three-letter [ISO4217](https://en.wikipedia.org/wiki/ISO_4217) code of the currency for the amount. Currently supported
	// currency values are enumerated above.
	Currency *Currency `json:"currency,omitempty"`
	// Entry mode of the payment details.
	EntryMode *EntryMode `json:"entry_mode,omitempty"`
	// Unique ID of the transaction.
	ID *string `json:"id,omitempty"`
	// Current number of the installment for deferred payments.
	// Min: 1
	InstallmentsCount *int `json:"installments_count,omitempty"`
	// Internal unique ID of the transaction on the SumUp platform.
	// Format: int64
	InternalID *int64 `json:"internal_id,omitempty"`
	// Unique code of the registered merchant to whom the payment is made.
	MerchantCode *string `json:"merchant_code,omitempty"`
	// Payment type used for the transaction.
	PaymentType *PaymentType `json:"payment_type,omitempty"`
	// Current status of the transaction.
	Status *CheckoutTransactionStatus `json:"status,omitempty"`
	// Date and time of the creation of the transaction. Response format expressed according to [ISO8601](https://en.wikipedia.org/wiki/ISO_8601) code.
	Timestamp *time.Time `json:"timestamp,omitempty"`
	// Amount of the tip (out of the total transaction amount).
	TipAmount *float32 `json:"tip_amount,omitempty"`
	// Transaction code returned by the acquirer/processing entity after processing the transaction.
	TransactionCode *string `json:"transaction_code,omitempty"`
	// Amount of the applicable VAT (out of the total transaction amount).
	VATAmount *float32 `json:"vat_amount,omitempty"`
}

// Current status of the transaction.
type CheckoutTransactionStatus string

const (
	CheckoutTransactionStatusCancelled  CheckoutTransactionStatus = "CANCELLED"
	CheckoutTransactionStatusFailed     CheckoutTransactionStatus = "FAILED"
	CheckoutTransactionStatusPending    CheckoutTransactionStatus = "PENDING"
	CheckoutTransactionStatusSuccessful CheckoutTransactionStatus = "SUCCESSFUL"
)

// Response returned when checkout processing requires an additional payer action, such as a 3DS challenge or
// a redirect to an external payment method page.
type CheckoutAccepted struct {
	// Instructions for the next action the payer or client must take.
	NextStep *CheckoutAcceptedNextStep `json:"next_step,omitempty"`
}

// Instructions for the next action the payer or client must take.
type CheckoutAcceptedNextStep struct {
	// Allowed presentation mechanisms for the next step. `iframe` means the flow can be embedded, while `browser` means
	// it can be completed through a full-page redirect.
	Mechanism []CheckoutAcceptedNextStepMechanism `json:"mechanism,omitempty"`
	// HTTP method to use when following the next step.
	Method *string `json:"method,omitempty"`
	// Parameters required to complete the next step. The exact keys depend on the payment provider and flow type.
	Payload *CheckoutAcceptedNextStepPayload `json:"payload,omitempty"`
	// Merchant URL where the payer returns after the external flow finishes.
	RedirectURL *string `json:"redirect_url,omitempty"`
	// URL to open or submit in order to continue processing.
	URL *string `json:"url,omitempty"`
}

// CheckoutAcceptedNextStepMechanism is a schema definition.
type CheckoutAcceptedNextStepMechanism string

const (
	CheckoutAcceptedNextStepMechanismBrowser CheckoutAcceptedNextStepMechanism = "browser"
	CheckoutAcceptedNextStepMechanismIframe  CheckoutAcceptedNextStepMechanism = "iframe"
)

// Parameters required to complete the next step. The exact keys depend on the payment provider and flow type.
type CheckoutAcceptedNextStepPayload struct {
	Md      *any `json:"md,omitempty"`
	PaReq   *any `json:"pa_req,omitempty"`
	TermURL *any `json:"term_url,omitempty"`
}

// Request body for creating a checkout before processing payment. Define the payment amount, currency, merchant,
// and optional customer or redirect behavior here.
type CheckoutCreateRequest struct {
	// Amount to be charged to the payer, expressed in major units.
	Amount float32 `json:"amount"`
	// Merchant-defined reference for the new checkout. It should be unique enough for you to identify the payment attempt
	// in your own systems.
	// Max length: 90
	CheckoutReference string `json:"checkout_reference"`
	// Three-letter [ISO4217](https://en.wikipedia.org/wiki/ISO_4217) code of the currency for the amount. Currently supported
	// currency values are enumerated above.
	Currency Currency `json:"currency"`
	// Merchant-scoped customer identifier. Required when setting up recurring payments and useful when the checkout
	// should be linked to a returning payer.
	CustomerID *string `json:"customer_id,omitempty"`
	// Short merchant-defined description shown in SumUp tools and reporting for easier identification of the checkout.
	Description *string `json:"description,omitempty"`
	// Merchant account that should receive the payment.
	MerchantCode string `json:"merchant_code"`
	// Business purpose of the checkout. Use `CHECKOUT` for a standard payment and `SETUP_RECURRING_PAYMENT` when
	// collecting consent and payment details for future recurring charges.
	// Default: CHECKOUT
	Purpose *CheckoutCreateRequestPurpose `json:"purpose,omitempty"`
	// URL where the payer should be sent after a redirect-based payment or SCA flow completes. This is required for
	// [APMs](https://developer.sumup.com/online-payments/apm/introduction) and recommended for card checkouts that
	// may require [3DS](https://developer.sumup.com/online-payments/features/3ds). If it is omitted, the [Payment Widget](https://developer.sumup.com/online-payments/checkouts)
	// can render the challenge in an iframe instead of using a full-page redirect.
	RedirectURL *string `json:"redirect_url,omitempty"`
	// Optional backend callback URL used by SumUp to notify your platform about processing updates for the checkout.
	//
	// Format: uri
	ReturnURL *string `json:"return_url,omitempty"`
	// Optional expiration timestamp. The checkout must be processed before this moment, otherwise it becomes unusable.
	// If omitted, the checkout does not have an explicit expiry time.
	ValidUntil *nullable.Field[time.Time] `json:"valid_until,omitempty"`
}

// Business purpose of the checkout. Use `CHECKOUT` for a standard payment and `SETUP_RECURRING_PAYMENT` when
// collecting consent and payment details for future recurring charges.
// Default: CHECKOUT
type CheckoutCreateRequestPurpose string

const (
	CheckoutCreateRequestPurposeCheckout              CheckoutCreateRequestPurpose = "CHECKOUT"
	CheckoutCreateRequestPurposeSetupRecurringPayment CheckoutCreateRequestPurpose = "SETUP_RECURRING_PAYMENT"
)

// Checkout resource returned after a synchronous processing attempt. In addition to the base checkout fields, it
// can include the resulting transaction identifiers and any newly created payment instrument token.
type CheckoutSuccess struct {
	// Amount to be charged to the payer, expressed in major units.
	Amount *float32 `json:"amount,omitempty"`
	// Merchant-defined reference for the checkout. Use it to correlate the SumUp checkout with your own order, cart,
	// subscription, or payment attempt in your systems.
	// Max length: 90
	CheckoutReference *string `json:"checkout_reference,omitempty"`
	// Three-letter [ISO4217](https://en.wikipedia.org/wiki/ISO_4217) code of the currency for the amount. Currently supported
	// currency values are enumerated above.
	Currency *Currency `json:"currency,omitempty"`
	// Merchant-scoped identifier of the customer associated with the checkout. Use it when storing payment instruments
	// or reusing saved customer context for recurring and returning-payer flows.
	CustomerID *string `json:"customer_id,omitempty"`
	// Date and time of the creation of the payment checkout. Response format expressed according to [ISO8601](https://en.wikipedia.org/wiki/ISO_8601) code.
	Date *time.Time `json:"date,omitempty"`
	// Short merchant-defined description shown in SumUp tools and reporting. Use it to make the checkout easier to
	// recognize in dashboards, support workflows, and reconciliation.
	Description *string `json:"description,omitempty"`
	// Unique SumUp identifier of the checkout resource.
	// Read only
	ID *string `json:"id,omitempty"`
	// Details of the mandate linked to the saved payment instrument.
	Mandate *MandateResponse `json:"mandate,omitempty"`
	// Merchant account that receives the payment.
	MerchantCode *string `json:"merchant_code,omitempty"`
	// Name of the merchant
	MerchantName *string `json:"merchant_name,omitempty"`
	// Details of the saved payment instrument created or reused during checkout processing.
	PaymentInstrument *CheckoutSuccessPaymentInstrument `json:"payment_instrument,omitempty"`
	// URL where the payer is redirected after a redirect-based payment or SCA flow completes.
	RedirectURL *string `json:"redirect_url,omitempty"`
	// Optional backend callback URL used by SumUp to notify your platform about processing updates for the checkout.
	//
	// Format: uri
	ReturnURL *string `json:"return_url,omitempty"`
	// Current high-level state of the checkout. `PENDING` means the checkout exists but is not yet completed, `PAID`
	// means a payment succeeded, `FAILED` means the latest processing attempt failed, and `EXPIRED` means the checkout
	// can no longer be processed.
	Status *CheckoutSuccessStatus `json:"status,omitempty"`
	// Transaction code of the successful transaction with which the payment for the checkout is completed.
	// Read only
	TransactionCode *string `json:"transaction_code,omitempty"`
	// Transaction ID of the successful transaction with which the payment for the checkout is completed.
	// Read only
	TransactionID *string `json:"transaction_id,omitempty"`
	// Payment attempts and resulting transaction records linked to this checkout. Use the Transactions endpoints when
	// you need the authoritative payment result and event history.
	// Unique items only
	Transactions []CheckoutSuccessTransaction `json:"transactions,omitempty"`
	// Optional expiration timestamp. The checkout must be processed before this moment, otherwise it becomes unusable.
	// If omitted, the checkout does not have an explicit expiry time.
	ValidUntil *nullable.Field[time.Time] `json:"valid_until,omitempty"`
}

// Current high-level state of the checkout. `PENDING` means the checkout exists but is not yet completed, `PAID`
// means a payment succeeded, `FAILED` means the latest processing attempt failed, and `EXPIRED` means the checkout
// can no longer be processed.
type CheckoutSuccessStatus string

const (
	CheckoutSuccessStatusExpired CheckoutSuccessStatus = "EXPIRED"
	CheckoutSuccessStatusFailed  CheckoutSuccessStatus = "FAILED"
	CheckoutSuccessStatusPaid    CheckoutSuccessStatus = "PAID"
	CheckoutSuccessStatusPending CheckoutSuccessStatus = "PENDING"
)

// CheckoutSuccessTransaction is a schema definition.
type CheckoutSuccessTransaction struct {
	// Total amount of the transaction.
	Amount *float32 `json:"amount,omitempty"`
	// Authorization code for the transaction sent by the payment card issuer or bank. Applicable only to card payments.
	AuthCode *string `json:"auth_code,omitempty"`
	// Three-letter [ISO4217](https://en.wikipedia.org/wiki/ISO_4217) code of the currency for the amount. Currently supported
	// currency values are enumerated above.
	Currency *Currency `json:"currency,omitempty"`
	// Entry mode of the payment details.
	EntryMode *EntryMode `json:"entry_mode,omitempty"`
	// Unique ID of the transaction.
	ID *string `json:"id,omitempty"`
	// Current number of the installment for deferred payments.
	// Min: 1
	InstallmentsCount *int `json:"installments_count,omitempty"`
	// Internal unique ID of the transaction on the SumUp platform.
	// Format: int64
	InternalID *int64 `json:"internal_id,omitempty"`
	// Unique code of the registered merchant to whom the payment is made.
	MerchantCode *string `json:"merchant_code,omitempty"`
	// Payment type used for the transaction.
	PaymentType *PaymentType `json:"payment_type,omitempty"`
	// Current status of the transaction.
	Status *CheckoutSuccessTransactionStatus `json:"status,omitempty"`
	// Date and time of the creation of the transaction. Response format expressed according to [ISO8601](https://en.wikipedia.org/wiki/ISO_8601) code.
	Timestamp *time.Time `json:"timestamp,omitempty"`
	// Amount of the tip (out of the total transaction amount).
	TipAmount *float32 `json:"tip_amount,omitempty"`
	// Transaction code returned by the acquirer/processing entity after processing the transaction.
	TransactionCode *string `json:"transaction_code,omitempty"`
	// Amount of the applicable VAT (out of the total transaction amount).
	VATAmount *float32 `json:"vat_amount,omitempty"`
}

// Current status of the transaction.
type CheckoutSuccessTransactionStatus string

const (
	CheckoutSuccessTransactionStatusCancelled  CheckoutSuccessTransactionStatus = "CANCELLED"
	CheckoutSuccessTransactionStatusFailed     CheckoutSuccessTransactionStatus = "FAILED"
	CheckoutSuccessTransactionStatusPending    CheckoutSuccessTransactionStatus = "PENDING"
	CheckoutSuccessTransactionStatusSuccessful CheckoutSuccessTransactionStatus = "SUCCESSFUL"
)

// Details of the saved payment instrument created or reused during checkout processing.
type CheckoutSuccessPaymentInstrument struct {
	// Token value
	Token *string `json:"token,omitempty"`
}

// Error message structure.
type DetailsError struct {
	// Details of the error.
	Details *string `json:"details,omitempty"`
	// List of violated validation constraints.
	FailedConstraints []DetailsErrorFailedConstraint `json:"failed_constraints,omitempty"`
	// The status code.
	Status *float64 `json:"status,omitempty"`
	// Short title of the error.
	Title *string `json:"title,omitempty"`
}

// DetailsErrorFailedConstraint is a schema definition.
type DetailsErrorFailedConstraint struct {
	Message   *string `json:"message,omitempty"`
	Reference *string `json:"reference,omitempty"`
}

func (e *DetailsError) Error() string {
	return fmt.Sprintf("details=%v, failed_constraints=%v, status=%v, title=%v", ptr.OrNil(e.Details), e.FailedConstraints, ptr.OrNil(e.Status), ptr.OrNil(e.Title))
}

var _ error = (*DetailsError)(nil)

// Mandate details used when a checkout should create a reusable card token for future recurring or merchant-initiated payments.
type MandatePayload struct {
	// Type of mandate to create for the saved payment instrument.
	Type MandatePayloadType `json:"type"`
	// Browser or client user agent observed when consent was collected.
	UserAgent string `json:"user_agent"`
	// IP address of the payer when the mandate was accepted.
	UserIP *string `json:"user_ip,omitempty"`
}

// Type of mandate to create for the saved payment instrument.
type MandatePayloadType string

const (
	MandatePayloadTypeRecurrent MandatePayloadType = "recurrent"
)

// Request body for attempting payment on an existing checkout. The required companion fields depend on the
// selected `payment_type`, for example card details, saved-card data, or payer information required by a
// specific payment method.
type ProcessCheckout struct {
	// Raw payment token object received from Apple Pay. Send the Apple Pay response payload as-is.
	ApplePay *json.RawMessage `json:"apple_pay,omitempty"`
	// __Required when payment type is `card`.__ Details of the payment card.
	Card *Card `json:"card,omitempty"`
	// Customer identifier associated with the saved payment instrument. Required when `token` is provided.
	CustomerID *string `json:"customer_id,omitempty"`
	// Raw `PaymentData` object received from Google Pay. Send the Google Pay response payload as-is.
	GooglePay *json.RawMessage `json:"google_pay,omitempty"`
	// Number of installments for deferred payments. Available only to merchant users in Brazil.
	// Min: 1
	// Max: 12
	Installments *int `json:"installments,omitempty"`
	// Mandate details used when a checkout should create a reusable card token for future recurring or merchant-initiated payments.
	Mandate *MandatePayload `json:"mandate,omitempty"`
	// Payment method used for this processing attempt. It determines which additional request fields are required.
	PaymentType ProcessCheckoutPaymentType `json:"payment_type"`
	// Personal details for the customer.
	PersonalDetails *PersonalDetails `json:"personal_details,omitempty"`
	// Saved-card token to use instead of raw card details when processing with a previously stored payment instrument.
	Token *string `json:"token,omitempty"`
}

// Payment method used for this processing attempt. It determines which additional request fields are required.
type ProcessCheckoutPaymentType string

const (
	ProcessCheckoutPaymentTypeApplePay   ProcessCheckoutPaymentType = "apple_pay"
	ProcessCheckoutPaymentTypeBancontact ProcessCheckoutPaymentType = "bancontact"
	ProcessCheckoutPaymentTypeBlik       ProcessCheckoutPaymentType = "blik"
	ProcessCheckoutPaymentTypeBoleto     ProcessCheckoutPaymentType = "boleto"
	ProcessCheckoutPaymentTypeCard       ProcessCheckoutPaymentType = "card"
	ProcessCheckoutPaymentTypeGooglePay  ProcessCheckoutPaymentType = "google_pay"
	ProcessCheckoutPaymentTypeIdeal      ProcessCheckoutPaymentType = "ideal"
)

type CheckoutsCreateParams = CheckoutCreateRequest

type CheckoutsProcessParams = ProcessCheckout

// CheckoutsListParams are query parameters for ListCheckouts.
type CheckoutsListParams struct {
	// Filters the list of checkout resources by the unique ID of the checkout.
	CheckoutReference *string
}

// QueryValues converts [CheckoutsListParams] into [url.Values].
func (p *CheckoutsListParams) QueryValues() url.Values {
	q := make(url.Values)

	if p.CheckoutReference != nil {
		q.Set("checkout_reference", *p.CheckoutReference)
	}

	return q
}

// CheckoutsListAvailablePaymentMethodsParams are query parameters for GetPaymentMethods.
type CheckoutsListAvailablePaymentMethodsParams struct {
	// The amount for which the payment methods should be eligible, in major units.
	Amount *float64
	// The currency for which the payment methods should be eligible.
	Currency *string
}

// QueryValues converts [CheckoutsListAvailablePaymentMethodsParams] into [url.Values].
func (p *CheckoutsListAvailablePaymentMethodsParams) QueryValues() url.Values {
	q := make(url.Values)

	if p.Amount != nil {
		q.Set("amount", strconv.FormatFloat(*p.Amount, 'f', -1, 64))
	}

	if p.Currency != nil {
		q.Set("currency", *p.Currency)
	}

	return q
}

// CheckoutsListResponse is a schema definition.
type CheckoutsListResponse []CheckoutSuccess

// CheckoutsListAvailablePaymentMethodsResponse is a schema definition.
type CheckoutsListAvailablePaymentMethodsResponse struct {
	AvailablePaymentMethods []CheckoutsListAvailablePaymentMethodsResponseAvailablePaymentMethod `json:"available_payment_methods,omitempty"`
}

// CheckoutsListAvailablePaymentMethodsResponseAvailablePaymentMethod is a schema definition.
type CheckoutsListAvailablePaymentMethodsResponseAvailablePaymentMethod struct {
	// The ID of the payment method.
	ID string `json:"id"`
}

// CheckoutsProcess400Response is a schema definition.
type CheckoutsProcess400Response json.RawMessage

func (e *CheckoutsProcess400Response) Error() string {
	return "CheckoutsProcess400Response"
}

var _ error = (*CheckoutsProcess400Response)(nil)

type CheckoutsProcessResponse struct {
	CheckoutSuccess  *CheckoutSuccess
	CheckoutAccepted *CheckoutAccepted
}

func (r *CheckoutsProcessResponse) AsCheckoutSuccess() (*CheckoutSuccess, bool) {
	if r.CheckoutSuccess != nil {
		return r.CheckoutSuccess, true
	}

	return nil, false
}

func (r *CheckoutsProcessResponse) AsCheckoutAccepted() (*CheckoutAccepted, bool) {
	if r.CheckoutAccepted != nil {
		return r.CheckoutAccepted, true
	}

	return nil, false
}

type CheckoutsClient struct {
	c *client.Client
}

func NewCheckoutsClient(c *client.Client) *CheckoutsClient {
	return &CheckoutsClient{c: c}
}

// Lists created checkout resources according to the applied `checkout_reference`.
func (c *CheckoutsClient) List(ctx context.Context, params CheckoutsListParams) (*CheckoutsListResponse, error) {
	path := fmt.Sprintf("/v0.1/checkouts")

	resp, err := c.c.Call(ctx, http.MethodGet, path, client.WithQueryValues(params.QueryValues()))
	if err != nil {
		return nil, fmt.Errorf("error building request: %v", err)
	}
	defer resp.Body.Close()

	switch resp.StatusCode {
	case http.StatusOK:
		var v CheckoutsListResponse
		if err := json.NewDecoder(resp.Body).Decode(&v); err != nil {
			return nil, fmt.Errorf("decode response: %s", err.Error())
		}

		return &v, nil
	case http.StatusUnauthorized:
		var apiErr Problem
		if err := json.NewDecoder(resp.Body).Decode(&apiErr); err != nil {
			return nil, fmt.Errorf("read error response: %s", err.Error())
		}

		return nil, &apiErr
	default:
		return nil, fmt.Errorf("unexpected response %d: %s", resp.StatusCode, http.StatusText(resp.StatusCode))
	}
}

// Creates a new payment checkout resource. The unique `checkout_reference` created by this request, is used
// for further manipulation of the checkout.
//
// For 3DS checkouts, add the `redirect_url` parameter to your request body schema.
//
// Follow by processing a checkout to charge the provided payment instrument.
func (c *CheckoutsClient) Create(ctx context.Context, body CheckoutsCreateParams) (*Checkout, error) {
	path := fmt.Sprintf("/v0.1/checkouts")

	resp, err := c.c.Call(ctx, http.MethodPost, path, client.WithJSONBody(body))
	if err != nil {
		return nil, fmt.Errorf("error building request: %v", err)
	}
	defer resp.Body.Close()

	switch resp.StatusCode {
	case http.StatusCreated:
		var v Checkout
		if err := json.NewDecoder(resp.Body).Decode(&v); err != nil {
			return nil, fmt.Errorf("decode response: %s", err.Error())
		}

		return &v, nil
	case http.StatusBadRequest:
		var apiErr ErrorExtended
		if err := json.NewDecoder(resp.Body).Decode(&apiErr); err != nil {
			return nil, fmt.Errorf("read error response: %s", err.Error())
		}

		return nil, &apiErr
	case http.StatusUnauthorized:
		var apiErr Problem
		if err := json.NewDecoder(resp.Body).Decode(&apiErr); err != nil {
			return nil, fmt.Errorf("read error response: %s", err.Error())
		}

		return nil, &apiErr
	case http.StatusForbidden:
		var apiErr ErrorForbidden
		if err := json.NewDecoder(resp.Body).Decode(&apiErr); err != nil {
			return nil, fmt.Errorf("read error response: %s", err.Error())
		}

		return nil, &apiErr
	case http.StatusConflict:
		var apiErr Error
		if err := json.NewDecoder(resp.Body).Decode(&apiErr); err != nil {
			return nil, fmt.Errorf("read error response: %s", err.Error())
		}

		return nil, &apiErr
	default:
		return nil, fmt.Errorf("unexpected response %d: %s", resp.StatusCode, http.StatusText(resp.StatusCode))
	}
}

// Get payment methods available for the given merchant to use with a checkout.
func (c *CheckoutsClient) ListAvailablePaymentMethods(ctx context.Context, merchantCode string, params CheckoutsListAvailablePaymentMethodsParams) (*CheckoutsListAvailablePaymentMethodsResponse, error) {
	path := fmt.Sprintf("/v0.1/merchants/%v/payment-methods", merchantCode)

	resp, err := c.c.Call(ctx, http.MethodGet, path, client.WithQueryValues(params.QueryValues()))
	if err != nil {
		return nil, fmt.Errorf("error building request: %v", err)
	}
	defer resp.Body.Close()

	switch resp.StatusCode {
	case http.StatusOK:
		var v CheckoutsListAvailablePaymentMethodsResponse
		if err := json.NewDecoder(resp.Body).Decode(&v); err != nil {
			return nil, fmt.Errorf("decode response: %s", err.Error())
		}

		return &v, nil
	case http.StatusBadRequest:
		var apiErr DetailsError
		if err := json.NewDecoder(resp.Body).Decode(&apiErr); err != nil {
			return nil, fmt.Errorf("read error response: %s", err.Error())
		}

		return nil, &apiErr
	default:
		return nil, fmt.Errorf("unexpected response %d: %s", resp.StatusCode, http.StatusText(resp.StatusCode))
	}
}

// Deactivates an identified checkout resource. If the checkout has already been processed it can not be deactivated.
func (c *CheckoutsClient) Deactivate(ctx context.Context, id string) (*Checkout, error) {
	path := fmt.Sprintf("/v0.1/checkouts/%v", id)

	resp, err := c.c.Call(ctx, http.MethodDelete, path)
	if err != nil {
		return nil, fmt.Errorf("error building request: %v", err)
	}
	defer resp.Body.Close()

	switch resp.StatusCode {
	case http.StatusOK:
		var v Checkout
		if err := json.NewDecoder(resp.Body).Decode(&v); err != nil {
			return nil, fmt.Errorf("decode response: %s", err.Error())
		}

		return &v, nil
	case http.StatusUnauthorized:
		var apiErr Problem
		if err := json.NewDecoder(resp.Body).Decode(&apiErr); err != nil {
			return nil, fmt.Errorf("read error response: %s", err.Error())
		}

		return nil, &apiErr
	case http.StatusNotFound:
		var apiErr Error
		if err := json.NewDecoder(resp.Body).Decode(&apiErr); err != nil {
			return nil, fmt.Errorf("read error response: %s", err.Error())
		}

		return nil, &apiErr
	case http.StatusConflict:
		var apiErr Error
		if err := json.NewDecoder(resp.Body).Decode(&apiErr); err != nil {
			return nil, fmt.Errorf("read error response: %s", err.Error())
		}

		return nil, &apiErr
	default:
		return nil, fmt.Errorf("unexpected response %d: %s", resp.StatusCode, http.StatusText(resp.StatusCode))
	}
}

// Retrieves an identified checkout resource. Use this request after processing a checkout to confirm its status
// and inform the end user respectively.
func (c *CheckoutsClient) Get(ctx context.Context, id string) (*CheckoutSuccess, error) {
	path := fmt.Sprintf("/v0.1/checkouts/%v", id)

	resp, err := c.c.Call(ctx, http.MethodGet, path)
	if err != nil {
		return nil, fmt.Errorf("error building request: %v", err)
	}
	defer resp.Body.Close()

	switch resp.StatusCode {
	case http.StatusOK:
		var v CheckoutSuccess
		if err := json.NewDecoder(resp.Body).Decode(&v); err != nil {
			return nil, fmt.Errorf("decode response: %s", err.Error())
		}

		return &v, nil
	case http.StatusUnauthorized:
		var apiErr Problem
		if err := json.NewDecoder(resp.Body).Decode(&apiErr); err != nil {
			return nil, fmt.Errorf("read error response: %s", err.Error())
		}

		return nil, &apiErr
	case http.StatusNotFound:
		var apiErr Error
		if err := json.NewDecoder(resp.Body).Decode(&apiErr); err != nil {
			return nil, fmt.Errorf("read error response: %s", err.Error())
		}

		return nil, &apiErr
	default:
		return nil, fmt.Errorf("unexpected response %d: %s", resp.StatusCode, http.StatusText(resp.StatusCode))
	}
}

// Processing a checkout will attempt to charge the provided payment instrument for the amount of the specified checkout
// resource initiated in the `Create a checkout` endpoint.
//
// Follow this request with `Retrieve a checkout` to confirm its status.
func (c *CheckoutsClient) Process(ctx context.Context, id string, body CheckoutsProcessParams) (*CheckoutsProcessResponse, error) {
	path := fmt.Sprintf("/v0.1/checkouts/%v", id)

	resp, err := c.c.Call(ctx, http.MethodPut, path, client.WithJSONBody(body))
	if err != nil {
		return nil, fmt.Errorf("error building request: %v", err)
	}
	defer resp.Body.Close()

	switch resp.StatusCode {
	case http.StatusOK:
		var v CheckoutSuccess
		if err := json.NewDecoder(resp.Body).Decode(&v); err != nil {
			return nil, fmt.Errorf("decode response: %s", err.Error())
		}

		return &CheckoutsProcessResponse{
			CheckoutSuccess: &v,
		}, nil
	case http.StatusAccepted:
		var v CheckoutAccepted
		if err := json.NewDecoder(resp.Body).Decode(&v); err != nil {
			return nil, fmt.Errorf("decode response: %s", err.Error())
		}

		return &CheckoutsProcessResponse{
			CheckoutAccepted: &v,
		}, nil
	case http.StatusBadRequest:
		var apiErr CheckoutsProcess400Response
		if err := json.NewDecoder(resp.Body).Decode(&apiErr); err != nil {
			return nil, fmt.Errorf("read error response: %s", err.Error())
		}

		return nil, &apiErr
	case http.StatusUnauthorized:
		var apiErr Problem
		if err := json.NewDecoder(resp.Body).Decode(&apiErr); err != nil {
			return nil, fmt.Errorf("read error response: %s", err.Error())
		}

		return nil, &apiErr
	case http.StatusNotFound:
		var apiErr Error
		if err := json.NewDecoder(resp.Body).Decode(&apiErr); err != nil {
			return nil, fmt.Errorf("read error response: %s", err.Error())
		}

		return nil, &apiErr
	case http.StatusConflict:
		var apiErr Error
		if err := json.NewDecoder(resp.Body).Decode(&apiErr); err != nil {
			return nil, fmt.Errorf("read error response: %s", err.Error())
		}

		return nil, &apiErr
	default:
		return nil, fmt.Errorf("unexpected response %d: %s", resp.StatusCode, http.StatusText(resp.StatusCode))
	}
}
