// Code generated by `go-sdk-gen`. DO NOT EDIT.

package sumup

import (
	"github.com/sumup/sumup-go/api_keys"
	"github.com/sumup/sumup-go/checkouts"
	"github.com/sumup/sumup-go/client"
	"github.com/sumup/sumup-go/customers"
	"github.com/sumup/sumup-go/members"
	"github.com/sumup/sumup-go/merchant"
	"github.com/sumup/sumup-go/payouts"
	"github.com/sumup/sumup-go/readers"
	"github.com/sumup/sumup-go/receipts"
	"github.com/sumup/sumup-go/subaccounts"
	"github.com/sumup/sumup-go/transactions"
)

type Client struct {
	c            *client.Client
	ApiKeys      *api_keys.ApiKeysService
	Checkouts    *checkouts.CheckoutsService
	Customers    *customers.CustomersService
	Members      *members.MembersService
	Merchant     *merchant.MerchantService
	Payouts      *payouts.PayoutsService
	Readers      *readers.ReadersService
	Receipts     *receipts.ReceiptsService
	Subaccounts  *subaccounts.SubaccountsService
	Transactions *transactions.TransactionsService
}

// NewClient creates new SumUp API client.
// The client is by default configured environment variables (`SUMUP_API_KEY`).
// To override the default configuration use [ClientOption]s.
func NewClient(opts ...client.ClientOption) *Client {
	client := client.New(opts...)

	c := &Client{c: client}
	c.ApiKeys = api_keys.NewApiKeysService(client)
	c.Checkouts = checkouts.NewCheckoutsService(client)
	c.Customers = customers.NewCustomersService(client)
	c.Members = members.NewMembersService(client)
	c.Merchant = merchant.NewMerchantService(client)
	c.Payouts = payouts.NewPayoutsService(client)
	c.Readers = readers.NewReadersService(client)
	c.Receipts = receipts.NewReceiptsService(client)
	c.Subaccounts = subaccounts.NewSubaccountsService(client)
	c.Transactions = transactions.NewTransactionsService(client)

	return c
}
