// Code generated by `gogenitor`. DO NOT EDIT.
package sumup

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"net/http"
)

// SchemasCreateManyResponse is a schema definition.
type SchemasCreateManyResponse struct {
	Acknowledged  *bool   `json:"acknowledged,omitempty"`
	BatchId       *string `json:"batch_id,omitempty"`
	InsertedCount *int    `json:"inserted_count,omitempty"`
}

// ImportExpensesBody is a schema definition.
type ImportExpensesBody struct {
	// The file to upload
	// Format: binary
	File string `json:"file"`
}

var _ error = (*GetImportSample4XXResponse)(nil)

// GetImportSample4XXResponse: Request validation error
type GetImportSample4XXResponse struct {
	Code       *string `json:"code,omitempty"`
	Error      *string `json:"error,omitempty"`
	Message    *string `json:"message,omitempty"`
	StatusCode *int    `json:"status_code,omitempty"`
}

func (e *GetImportSample4XXResponse) Error() string {
	return fmt.Sprintf("code=%v, error=%v, message=%v, statusCode=%v", e.Code, e.Error, e.Message, e.StatusCode)
}

var _ error = (*GetImportSample5XXResponse)(nil)

// GetImportSample5XXResponse: Internal server error
type GetImportSample5XXResponse struct {
	Code       *string `json:"code,omitempty"`
	Error      *string `json:"error,omitempty"`
	Message    *string `json:"message,omitempty"`
	StatusCode *int    `json:"status_code,omitempty"`
}

func (e *GetImportSample5XXResponse) Error() string {
	return fmt.Sprintf("code=%v, error=%v, message=%v, statusCode=%v", e.Code, e.Error, e.Message, e.StatusCode)
}

var _ error = (*ImportExpenses400Response)(nil)

// ImportExpenses400Response is a schema definition.
type ImportExpenses400Response struct {
	// INVALID_IMPORT_ROW
	Code *string `json:"code,omitempty"`
	// Bad Request
	Error *string `json:"error,omitempty"`
	// a descriptive message of the validation error
	Message *string `json:"message,omitempty"`
	// 400
	StatusCode *string `json:"status_code,omitempty"`
}

func (e *ImportExpenses400Response) Error() string {
	return fmt.Sprintf("code=%v, error=%v, message=%v, statusCode=%v", e.Code, e.Error, e.Message, e.StatusCode)
}

var _ error = (*ImportExpenses4XXResponse)(nil)

// ImportExpenses4XXResponse: Request validation error
type ImportExpenses4XXResponse struct {
	Code       *string `json:"code,omitempty"`
	Error      *string `json:"error,omitempty"`
	Message    *string `json:"message,omitempty"`
	StatusCode *int    `json:"status_code,omitempty"`
}

func (e *ImportExpenses4XXResponse) Error() string {
	return fmt.Sprintf("code=%v, error=%v, message=%v, statusCode=%v", e.Code, e.Error, e.Message, e.StatusCode)
}

var _ error = (*ImportExpenses5XXResponse)(nil)

// ImportExpenses5XXResponse: Internal server error
type ImportExpenses5XXResponse struct {
	Code       *string `json:"code,omitempty"`
	Error      *string `json:"error,omitempty"`
	Message    *string `json:"message,omitempty"`
	StatusCode *int    `json:"status_code,omitempty"`
}

func (e *ImportExpenses5XXResponse) Error() string {
	return fmt.Sprintf("code=%v, error=%v, message=%v, statusCode=%v", e.Code, e.Error, e.Message, e.StatusCode)
}

var _ error = (*DeleteImportBatch4XXResponse)(nil)

// DeleteImportBatch4XXResponse: Request validation error
type DeleteImportBatch4XXResponse struct {
	Code       *string `json:"code,omitempty"`
	Error      *string `json:"error,omitempty"`
	Message    *string `json:"message,omitempty"`
	StatusCode *int    `json:"status_code,omitempty"`
}

func (e *DeleteImportBatch4XXResponse) Error() string {
	return fmt.Sprintf("code=%v, error=%v, message=%v, statusCode=%v", e.Code, e.Error, e.Message, e.StatusCode)
}

var _ error = (*DeleteImportBatch5XXResponse)(nil)

// DeleteImportBatch5XXResponse: Internal server error
type DeleteImportBatch5XXResponse struct {
	Code       *string `json:"code,omitempty"`
	Error      *string `json:"error,omitempty"`
	Message    *string `json:"message,omitempty"`
	StatusCode *int    `json:"status_code,omitempty"`
}

func (e *DeleteImportBatch5XXResponse) Error() string {
	return fmt.Sprintf("code=%v, error=%v, message=%v, statusCode=%v", e.Code, e.Error, e.Message, e.StatusCode)
}

type ImportService service

// GetImportSample: Get a sample file for importing expenses
func (s *ImportService) GetImportSample(ctx context.Context, merchantCode string) error {
	path := fmt.Sprintf("/merchants/%v/expenses/import/sample", merchantCode)

	req, err := s.client.NewRequest(ctx, http.MethodGet, path, http.NoBody)
	if err != nil {
		return fmt.Errorf("error building request: %v", err)
	}

	resp, err := s.client.Do(req)
	if err != nil {
		return fmt.Errorf("error sending request: %v", err)
	}
	defer resp.Body.Close()

	switch resp.StatusCode {
	case http.StatusOK:
		return nil
	case http.StatusBadRequest:
		var apiErr GetImportSample4XXResponse
		if err := json.NewDecoder(resp.Body).Decode(&apiErr); err != nil {
			return fmt.Errorf("read error response: %s", err.Error())
		}

		return &apiErr
	case http.StatusInternalServerError:
		var apiErr GetImportSample5XXResponse
		if err := json.NewDecoder(resp.Body).Decode(&apiErr); err != nil {
			return fmt.Errorf("read error response: %s", err.Error())
		}

		return &apiErr
	default:
		return fmt.Errorf("unexpected response %d: %s", resp.StatusCode, http.StatusText(resp.StatusCode))
	}
}

// ImportExpenses: Importing expenses data
func (s *ImportService) ImportExpenses(ctx context.Context, merchantCode string, body ImportExpensesBody) (*SchemasCreateManyResponse, error) {
	buf := new(bytes.Buffer)
	if err := json.NewEncoder(buf).Encode(body); err != nil {
		return nil, fmt.Errorf("encoding json body request failed: %v", err)
	}

	path := fmt.Sprintf("/merchants/%v/expenses/import", merchantCode)

	req, err := s.client.NewRequest(ctx, http.MethodPost, path, buf)
	if err != nil {
		return nil, fmt.Errorf("error building request: %v", err)
	}

	resp, err := s.client.Do(req)
	if err != nil {
		return nil, fmt.Errorf("error sending request: %v", err)
	}
	defer resp.Body.Close()

	switch resp.StatusCode {
	case http.StatusOK:
		var v SchemasCreateManyResponse
		if err := json.NewDecoder(resp.Body).Decode(&v); err != nil {
			return nil, fmt.Errorf("decode response: %s", err.Error())
		}

		return &v, nil
	case http.StatusBadRequest:
		var apiErr ImportExpenses400Response
		if err := json.NewDecoder(resp.Body).Decode(&apiErr); err != nil {
			return nil, fmt.Errorf("read error response: %s", err.Error())
		}

		return nil, &apiErr
	case http.StatusBadRequest:
		var apiErr ImportExpenses4XXResponse
		if err := json.NewDecoder(resp.Body).Decode(&apiErr); err != nil {
			return nil, fmt.Errorf("read error response: %s", err.Error())
		}

		return nil, &apiErr
	case http.StatusInternalServerError:
		var apiErr ImportExpenses5XXResponse
		if err := json.NewDecoder(resp.Body).Decode(&apiErr); err != nil {
			return nil, fmt.Errorf("read error response: %s", err.Error())
		}

		return nil, &apiErr
	default:
		return nil, fmt.Errorf("unexpected response %d: %s", resp.StatusCode, http.StatusText(resp.StatusCode))
	}
}

// DeleteImportBatch: Delete an import batch
func (s *ImportService) DeleteImportBatch(ctx context.Context, merchantCode string, batchId string) (*SchemasUpdateResponse, error) {
	path := fmt.Sprintf("/merchants/%v/expenses/import/%v", merchantCode, batchId)

	req, err := s.client.NewRequest(ctx, http.MethodDelete, path, http.NoBody)
	if err != nil {
		return nil, fmt.Errorf("error building request: %v", err)
	}

	resp, err := s.client.Do(req)
	if err != nil {
		return nil, fmt.Errorf("error sending request: %v", err)
	}
	defer resp.Body.Close()

	switch resp.StatusCode {
	case http.StatusOK:
		var v SchemasUpdateResponse
		if err := json.NewDecoder(resp.Body).Decode(&v); err != nil {
			return nil, fmt.Errorf("decode response: %s", err.Error())
		}

		return &v, nil
	case http.StatusBadRequest:
		var apiErr DeleteImportBatch4XXResponse
		if err := json.NewDecoder(resp.Body).Decode(&apiErr); err != nil {
			return nil, fmt.Errorf("read error response: %s", err.Error())
		}

		return nil, &apiErr
	case http.StatusInternalServerError:
		var apiErr DeleteImportBatch5XXResponse
		if err := json.NewDecoder(resp.Body).Decode(&apiErr); err != nil {
			return nil, fmt.Errorf("read error response: %s", err.Error())
		}

		return nil, &apiErr
	default:
		return nil, fmt.Errorf("unexpected response %d: %s", resp.StatusCode, http.StatusText(resp.StatusCode))
	}
}
