// Code generated by `go-sdk-gen`. DO NOT EDIT.

package sumup

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"strconv"

	"github.com/sumup/sumup-go/client"
	"github.com/sumup/sumup-go/datetime"
)

// A single payout-related record.
//
// A record can represent either:
// - an actual payout sent to the merchant (`type = PAYOUT`)
// - a deduction applied against merchant funds for a refund, chargeback, direct debit return, or balance adjustment
type FinancialPayout struct {
	// Amount of the payout or deduction in major units.
	Amount float32 `json:"amount"`
	// Three-letter ISO 4217 currency code of the payout.
	Currency string `json:"currency"`
	// Payout date associated with the record, in `YYYY-MM-DD` format.
	// Format: date
	Date datetime.Date `json:"date"`
	// Fee amount associated with the payout record, in major units.
	Fee float32 `json:"fee"`
	// Unique identifier of the payout-related record.
	ID int `json:"id"`
	// Processor or payout reference associated with the record.
	Reference string `json:"reference"`
	// Merchant-facing outcome of the payout record.
	Status FinancialPayoutStatus `json:"status"`
	// Transaction code of the original sale associated with the payout or deduction.
	TransactionCode string `json:"transaction_code"`
	// High-level payout record category.
	Type FinancialPayoutType `json:"type"`
}

// Merchant-facing outcome of the payout record.
type FinancialPayoutStatus string

const (
	FinancialPayoutStatusFailed     FinancialPayoutStatus = "FAILED"
	FinancialPayoutStatusSuccessful FinancialPayoutStatus = "SUCCESSFUL"
)

// High-level payout record category.
type FinancialPayoutType string

const (
	FinancialPayoutTypeBalanceDeduction    FinancialPayoutType = "BALANCE_DEDUCTION"
	FinancialPayoutTypeChargeBackDeduction FinancialPayoutType = "CHARGE_BACK_DEDUCTION"
	FinancialPayoutTypeDdReturnDeduction   FinancialPayoutType = "DD_RETURN_DEDUCTION"
	FinancialPayoutTypePayout              FinancialPayoutType = "PAYOUT"
	FinancialPayoutTypeRefundDeduction     FinancialPayoutType = "REFUND_DEDUCTION"
)

// Ordered list of payout and payout-deduction records.
type FinancialPayouts []FinancialPayout

// PayoutsListFormat is a schema definition.
// Default: json
type PayoutsListFormat string

const (
	PayoutsListFormatCSV  PayoutsListFormat = "csv"
	PayoutsListFormatJSON PayoutsListFormat = "json"
)

// PayoutsListOrder is a schema definition.
// Default: asc
type PayoutsListOrder string

const (
	PayoutsListOrderASC  PayoutsListOrder = "asc"
	PayoutsListOrderDESC PayoutsListOrder = "desc"
)

// PayoutsListParams are query parameters for ListPayoutsV1.
type PayoutsListParams struct {
	// End date of the payout period filter, inclusive, in [ISO8601](https://en.wikipedia.org/wiki/ISO_8601) `date`
	// format (`YYYY-MM-DD`). Must be greater than or equal to `start_date`.
	EndDate datetime.Date
	// Response format for the payout list.
	Format *PayoutsListFormat
	// Maximum number of payout records to return.
	Limit *int
	// Sort direction for the returned payouts.
	Order *PayoutsListOrder
	// Start date of the payout period filter, inclusive, in [ISO8601](https://en.wikipedia.org/wiki/ISO_8601) `date`
	// format (`YYYY-MM-DD`).
	StartDate datetime.Date
}

// QueryValues converts [PayoutsListParams] into [url.Values].
func (p *PayoutsListParams) QueryValues() url.Values {
	q := make(url.Values)

	q.Set("end_date", p.EndDate.String())

	if p.Format != nil {
		q.Set("format", string(*p.Format))
	}

	if p.Limit != nil {
		q.Set("limit", strconv.Itoa(*p.Limit))
	}

	if p.Order != nil {
		q.Set("order", string(*p.Order))
	}

	q.Set("start_date", p.StartDate.String())

	return q
}

// PayoutsList400Response is a schema definition.
type PayoutsList400Response []ErrorExtended

func (e *PayoutsList400Response) Error() string {
	return "PayoutsList400Response"
}

var _ error = (*PayoutsList400Response)(nil)

// PayoutsClient provides access to the Payouts API.
//
// The Payouts model will allow you to track funds you’ve received from SumUp.
//
// You can receive a detailed payouts list with information like dates, fees, references and statuses, using the
// `List payouts` endpoint.
type PayoutsClient struct {
	c *client.Client
}

func NewPayoutsClient(c *client.Client) *PayoutsClient {
	return &PayoutsClient{c: c}
}

// Lists payout and payout-deduction records for the specified merchant account within the requested date range.
//
// The response can include:
// - regular payouts (`type = PAYOUT`)
// - deduction records for refunds, chargebacks, direct debit returns, or balance adjustments
//
// Results are sorted by payout date in the requested `order`.
func (c *PayoutsClient) List(ctx context.Context, merchantCode string, params PayoutsListParams) (*FinancialPayouts, error) {
	path := fmt.Sprintf("/v1.0/merchants/%v/payouts", merchantCode)

	resp, err := c.c.Call(ctx, http.MethodGet, path, client.WithQueryValues(params.QueryValues()))
	if err != nil {
		return nil, fmt.Errorf("call %s %s: %w", http.MethodGet, path, err)
	}
	defer func() {
		_ = resp.Body.Close()
	}()

	switch resp.StatusCode {
	case http.StatusOK:
		var v FinancialPayouts
		if err := json.NewDecoder(resp.Body).Decode(&v); err != nil {
			return nil, fmt.Errorf("decode response: %s", err.Error())
		}

		return &v, nil
	case http.StatusBadRequest:
		var apiErr PayoutsList400Response
		if err := json.NewDecoder(resp.Body).Decode(&apiErr); err != nil {
			return nil, fmt.Errorf("read error response: %s", err.Error())
		}

		return nil, &apiErr
	case http.StatusUnauthorized:
		var apiErr Problem
		if err := json.NewDecoder(resp.Body).Decode(&apiErr); err != nil {
			return nil, fmt.Errorf("read error response: %s", err.Error())
		}

		return nil, &apiErr
	default:
		return nil, fmt.Errorf("unexpected response %d: %s", resp.StatusCode, http.StatusText(resp.StatusCode))
	}
}
