// Code generated by `go-sdk-gen`. DO NOT EDIT.

package sumup

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"strconv"

	"github.com/sumup/sumup-go/client"
	"github.com/sumup/sumup-go/datetime"
)

// FinancialPayout is a schema definition.
type FinancialPayout struct {
	Amount   *float32 `json:"amount,omitempty"`
	Currency *string  `json:"currency,omitempty"`
	// Format: date
	Date            *datetime.Date         `json:"date,omitempty"`
	Fee             *float32               `json:"fee,omitempty"`
	ID              *int                   `json:"id,omitempty"`
	Reference       *string                `json:"reference,omitempty"`
	Status          *FinancialPayoutStatus `json:"status,omitempty"`
	TransactionCode *string                `json:"transaction_code,omitempty"`
	Type            *FinancialPayoutType   `json:"type,omitempty"`
}

// FinancialPayoutStatus is a schema definition.
type FinancialPayoutStatus string

const (
	FinancialPayoutStatusFailed     FinancialPayoutStatus = "FAILED"
	FinancialPayoutStatusSuccessful FinancialPayoutStatus = "SUCCESSFUL"
)

// FinancialPayoutType is a schema definition.
type FinancialPayoutType string

const (
	FinancialPayoutTypeBalanceDeduction    FinancialPayoutType = "BALANCE_DEDUCTION"
	FinancialPayoutTypeChargeBackDeduction FinancialPayoutType = "CHARGE_BACK_DEDUCTION"
	FinancialPayoutTypeDdReturnDeduction   FinancialPayoutType = "DD_RETURN_DEDUCTION"
	FinancialPayoutTypePayout              FinancialPayoutType = "PAYOUT"
	FinancialPayoutTypeRefundDeduction     FinancialPayoutType = "REFUND_DEDUCTION"
)

// List of payout summaries.
type FinancialPayouts []FinancialPayout

// PayoutsListDeprecatedFormat is a schema definition.
type PayoutsListDeprecatedFormat string

const (
	PayoutsListDeprecatedFormatCSV  PayoutsListDeprecatedFormat = "csv"
	PayoutsListDeprecatedFormatJSON PayoutsListDeprecatedFormat = "json"
)

// PayoutsListDeprecatedOrder is a schema definition.
type PayoutsListDeprecatedOrder string

const (
	PayoutsListDeprecatedOrderASC  PayoutsListDeprecatedOrder = "asc"
	PayoutsListDeprecatedOrderDESC PayoutsListDeprecatedOrder = "desc"
)

// PayoutsListDeprecatedParams are query parameters for ListPayouts.
type PayoutsListDeprecatedParams struct {
	// End date (in [ISO8601](https://en.wikipedia.org/wiki/ISO_8601) format).
	EndDate datetime.Date
	Format  *PayoutsListDeprecatedFormat
	Limit   *int
	Order   *PayoutsListDeprecatedOrder
	// Start date (in [ISO8601](https://en.wikipedia.org/wiki/ISO_8601) format).
	StartDate datetime.Date
}

// QueryValues converts [PayoutsListDeprecatedParams] into [url.Values].
func (p *PayoutsListDeprecatedParams) QueryValues() url.Values {
	q := make(url.Values)

	q.Set("end_date", p.EndDate.String())

	if p.Format != nil {
		q.Set("format", string(*p.Format))
	}

	if p.Limit != nil {
		q.Set("limit", strconv.Itoa(*p.Limit))
	}

	if p.Order != nil {
		q.Set("order", string(*p.Order))
	}

	q.Set("start_date", p.StartDate.String())

	return q
}

// PayoutsListFormat is a schema definition.
type PayoutsListFormat string

const (
	PayoutsListFormatCSV  PayoutsListFormat = "csv"
	PayoutsListFormatJSON PayoutsListFormat = "json"
)

// PayoutsListOrder is a schema definition.
type PayoutsListOrder string

const (
	PayoutsListOrderASC  PayoutsListOrder = "asc"
	PayoutsListOrderDESC PayoutsListOrder = "desc"
)

// PayoutsListParams are query parameters for ListPayoutsV1.
type PayoutsListParams struct {
	// End date (in [ISO8601](https://en.wikipedia.org/wiki/ISO_8601) format).
	EndDate datetime.Date
	Format  *PayoutsListFormat
	Limit   *int
	Order   *PayoutsListOrder
	// Start date (in [ISO8601](https://en.wikipedia.org/wiki/ISO_8601) format).
	StartDate datetime.Date
}

// QueryValues converts [PayoutsListParams] into [url.Values].
func (p *PayoutsListParams) QueryValues() url.Values {
	q := make(url.Values)

	q.Set("end_date", p.EndDate.String())

	if p.Format != nil {
		q.Set("format", string(*p.Format))
	}

	if p.Limit != nil {
		q.Set("limit", strconv.Itoa(*p.Limit))
	}

	if p.Order != nil {
		q.Set("order", string(*p.Order))
	}

	q.Set("start_date", p.StartDate.String())

	return q
}

// PayoutsListDeprecated400Response is a schema definition.
type PayoutsListDeprecated400Response []ErrorExtended

func (e *PayoutsListDeprecated400Response) Error() string {
	return "PayoutsListDeprecated400Response"
}

var _ error = (*PayoutsListDeprecated400Response)(nil)

// PayoutsList400Response is a schema definition.
type PayoutsList400Response []ErrorExtended

func (e *PayoutsList400Response) Error() string {
	return "PayoutsList400Response"
}

var _ error = (*PayoutsList400Response)(nil)

type PayoutsClient struct {
	c *client.Client
}

func NewPayoutsClient(c *client.Client) *PayoutsClient {
	return &PayoutsClient{c: c}
}

// Lists ordered payouts for the merchant profile.
// Deprecated: this operation is deprecated
func (c *PayoutsClient) ListDeprecated(ctx context.Context, params PayoutsListDeprecatedParams) (*FinancialPayouts, error) {
	path := fmt.Sprintf("/v0.1/me/financials/payouts")

	resp, err := c.c.Call(ctx, http.MethodGet, path, client.WithQueryValues(params.QueryValues()))
	if err != nil {
		return nil, fmt.Errorf("error building request: %v", err)
	}
	defer resp.Body.Close()

	switch resp.StatusCode {
	case http.StatusOK:
		var v FinancialPayouts
		if err := json.NewDecoder(resp.Body).Decode(&v); err != nil {
			return nil, fmt.Errorf("decode response: %s", err.Error())
		}

		return &v, nil
	case http.StatusBadRequest:
		var apiErr PayoutsListDeprecated400Response
		if err := json.NewDecoder(resp.Body).Decode(&apiErr); err != nil {
			return nil, fmt.Errorf("read error response: %s", err.Error())
		}

		return nil, &apiErr
	case http.StatusUnauthorized:
		var apiErr Problem
		if err := json.NewDecoder(resp.Body).Decode(&apiErr); err != nil {
			return nil, fmt.Errorf("read error response: %s", err.Error())
		}

		return nil, &apiErr
	default:
		return nil, fmt.Errorf("unexpected response %d: %s", resp.StatusCode, http.StatusText(resp.StatusCode))
	}
}

// Lists ordered payouts for the merchant profile.
func (c *PayoutsClient) List(ctx context.Context, merchantCode string, params PayoutsListParams) (*FinancialPayouts, error) {
	path := fmt.Sprintf("/v1.0/merchants/%v/payouts", merchantCode)

	resp, err := c.c.Call(ctx, http.MethodGet, path, client.WithQueryValues(params.QueryValues()))
	if err != nil {
		return nil, fmt.Errorf("error building request: %v", err)
	}
	defer resp.Body.Close()

	switch resp.StatusCode {
	case http.StatusOK:
		var v FinancialPayouts
		if err := json.NewDecoder(resp.Body).Decode(&v); err != nil {
			return nil, fmt.Errorf("decode response: %s", err.Error())
		}

		return &v, nil
	case http.StatusBadRequest:
		var apiErr PayoutsList400Response
		if err := json.NewDecoder(resp.Body).Decode(&apiErr); err != nil {
			return nil, fmt.Errorf("read error response: %s", err.Error())
		}

		return nil, &apiErr
	case http.StatusUnauthorized:
		var apiErr Problem
		if err := json.NewDecoder(resp.Body).Decode(&apiErr); err != nil {
			return nil, fmt.Errorf("read error response: %s", err.Error())
		}

		return nil, &apiErr
	default:
		return nil, fmt.Errorf("unexpected response %d: %s", resp.StatusCode, http.StatusText(resp.StatusCode))
	}
}
