// Code generated by `go-sdk-gen`. DO NOT EDIT.

package sumup

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"strconv"
	"time"

	"github.com/sumup/sumup-go/client"
)

// Receipt details for a transaction.
type Receipt struct {
	// Acquirer-specific metadata related to the card authorization.
	AcquirerData *ReceiptAcquirerData `json:"acquirer_data,omitempty"`
	// EMV-specific metadata returned for card-present payments.
	EmvData *json.RawMessage `json:"emv_data,omitempty"`
	// Receipt merchant data
	MerchantData *ReceiptMerchantData `json:"merchant_data,omitempty"`
	// Transaction information.
	TransactionData *ReceiptTransaction `json:"transaction_data,omitempty"`
}

// Acquirer-specific metadata related to the card authorization.
type ReceiptAcquirerData struct {
	AuthorizationCode *string `json:"authorization_code,omitempty"`
	LocalTime         *string `json:"local_time,omitempty"`
	ReturnCode        *string `json:"return_code,omitempty"`
	Tid               *string `json:"tid,omitempty"`
}

// Payment card details displayed on the receipt.
type ReceiptCard struct {
	// Card last 4 digits.
	Last4Digits *string `json:"last_4_digits,omitempty"`
	// Card Scheme.
	Type *string `json:"type,omitempty"`
}

// Transaction event details as rendered on the receipt.
type ReceiptEvent struct {
	// Amount of the event.
	// Format: double
	Amount *json.Number `json:"amount,omitempty"`
	// Unique ID of the transaction event.
	// Format: int64
	ID *EventID `json:"id,omitempty"`
	// Receipt number associated with the event.
	ReceiptNo *string `json:"receipt_no,omitempty"`
	// Status of the transaction event.
	//
	// Not every value is used for every event type.
	//
	// - `PENDING`: The event has been created but is not final yet. Used for events that are still being processed and
	// whose final outcome is not known yet.
	// - `SCHEDULED`: The event is planned for a future payout cycle but has not been executed yet. This applies to
	// payout events before money is actually sent out.
	// - `RECONCILED`: The underlying payment has been matched with settlement data and is ready to continue through
	// payout processing, but the funds have not been paid out yet. This applies to payout events.
	// - `PAID_OUT`: The payout event has been completed and the funds were included in a merchant payout.
	// - `REFUNDED`: A refund event has been accepted and recorded in the refund flow. This is the status returned for
	// refund events once the transaction amount is being or has been returned to the payer.
	// - `SUCCESSFUL`: The event completed successfully. Use this as the generic terminal success status for event
	// types that do not expose a more specific business outcome such as `PAID_OUT` or `REFUNDED`.
	// - `FAILED`: The event could not be completed. Typical examples are a payout that could not be executed or
	// an event that was rejected during processing.
	Status *EventStatus `json:"status,omitempty"`
	// Date and time of the transaction event.
	Timestamp *time.Time `json:"timestamp,omitempty"`
	// Unique ID of the transaction.
	TransactionID *TransactionID `json:"transaction_id,omitempty"`
	// Type of the transaction event.
	Type *EventType `json:"type,omitempty"`
}

// Receipt merchant data
type ReceiptMerchantData struct {
	// Locale used for rendering localized receipt fields.
	Locale *string `json:"locale,omitempty"`
	// Merchant profile details displayed on the receipt.
	MerchantProfile *ReceiptMerchantDataMerchantProfile `json:"merchant_profile,omitempty"`
}

// Merchant profile details displayed on the receipt.
type ReceiptMerchantDataMerchantProfile struct {
	Address                   *ReceiptMerchantDataMerchantProfileAddress `json:"address,omitempty"`
	BusinessName              *string                                    `json:"business_name,omitempty"`
	CompanyRegistrationNumber *string                                    `json:"company_registration_number,omitempty"`
	Email                     *string                                    `json:"email,omitempty"`
	Language                  *string                                    `json:"language,omitempty"`
	MerchantCode              *string                                    `json:"merchant_code,omitempty"`
	VATID                     *string                                    `json:"vat_id,omitempty"`
	Website                   *string                                    `json:"website,omitempty"`
}

// ReceiptMerchantDataMerchantProfileAddress is a schema definition.
type ReceiptMerchantDataMerchantProfileAddress struct {
	AddressLine1      *string `json:"address_line_1,omitempty"`
	AddressLine2      *string `json:"address_line_2,omitempty"`
	City              *string `json:"city,omitempty"`
	Country           *string `json:"country,omitempty"`
	CountryEnName     *string `json:"country_en_name,omitempty"`
	CountryNativeName *string `json:"country_native_name,omitempty"`
	Landline          *string `json:"landline,omitempty"`
	PostCode          *string `json:"post_code,omitempty"`
	RegionName        *string `json:"region_name,omitempty"`
}

// Card reader details displayed on the receipt.
type ReceiptReader struct {
	// Reader serial number.
	Code *string `json:"code,omitempty"`
	// Reader type.
	Type *string `json:"type,omitempty"`
}

// Transaction information.
type ReceiptTransaction struct {
	// Transaction amount.
	Amount *string `json:"amount,omitempty"`
	// Payment card details displayed on the receipt.
	Card *ReceiptCard `json:"card,omitempty"`
	// Card reader details displayed on the receipt.
	CardReader *ReceiptReader `json:"card_reader,omitempty"`
	// Transaction currency.
	Currency *string `json:"currency,omitempty"`
	// Transaction entry mode.
	EntryMode *string `json:"entry_mode,omitempty"`
	// Events
	Events []ReceiptEvent `json:"events,omitempty"`
	// Number of installments.
	InstallmentsCount *int `json:"installments_count,omitempty"`
	// Merchant code.
	MerchantCode *string `json:"merchant_code,omitempty"`
	// Transaction type.
	PaymentType *string `json:"payment_type,omitempty"`
	// Debit/Credit.
	ProcessAs *ReceiptTransactionProcessA `json:"process_as,omitempty"`
	// Products
	Products []ReceiptTransactionProduct `json:"products,omitempty"`
	// Receipt number
	ReceiptNo *string `json:"receipt_no,omitempty"`
	// Transaction processing status.
	Status *string `json:"status,omitempty"`
	// Time created at.
	Timestamp *time.Time `json:"timestamp,omitempty"`
	// Tip amount (included in transaction amount).
	TipAmount *string `json:"tip_amount,omitempty"`
	// Transaction code.
	TransactionCode *string `json:"transaction_code,omitempty"`
	// Unique ID of the transaction.
	TransactionID *TransactionID `json:"transaction_id,omitempty"`
	// Transaction VAT amount.
	VATAmount *string `json:"vat_amount,omitempty"`
	// Vat rates.
	VATRates []ReceiptTransactionVATRate `json:"vat_rates,omitempty"`
	// Cardholder verification method.
	VerificationMethod *string `json:"verification_method,omitempty"`
}

// Debit/Credit.
type ReceiptTransactionProcessA string

const (
	ReceiptTransactionProcessACredit ReceiptTransactionProcessA = "CREDIT"
	ReceiptTransactionProcessADebit  ReceiptTransactionProcessA = "DEBIT"
)

// ReceiptTransactionProduct is a schema definition.
type ReceiptTransactionProduct struct {
	// Product description
	Description *string `json:"description,omitempty"`
	// Product name
	Name *string `json:"name,omitempty"`
	// Product price
	// Format: double
	Price *json.Number `json:"price,omitempty"`
	// Product price including VAT
	// Format: double
	PriceWithVAT *json.Number `json:"price_with_vat,omitempty"`
	// Product quantity
	// Format: int64
	Quantity *int64 `json:"quantity,omitempty"`
	// VAT amount for a single product
	// Format: double
	SingleVATAmount *json.Number `json:"single_vat_amount,omitempty"`
	// Quantity x product price
	// Format: double
	TotalPrice *json.Number `json:"total_price,omitempty"`
	// Total price including VAT
	// Format: double
	TotalWithVAT *json.Number `json:"total_with_vat,omitempty"`
	// VAT amount
	// Format: double
	VATAmount *json.Number `json:"vat_amount,omitempty"`
	// VAT rate
	// Format: double
	VATRate *json.Number `json:"vat_rate,omitempty"`
}

// ReceiptTransactionVATRate is a schema definition.
type ReceiptTransactionVATRate struct {
	// Gross
	Gross *float32 `json:"gross,omitempty"`
	// Net
	Net *float32 `json:"net,omitempty"`
	// Rate
	Rate *float32 `json:"rate,omitempty"`
	// Vat
	VAT *float32 `json:"vat,omitempty"`
}

// ReceiptsGetParams are query parameters for GetReceipt.
type ReceiptsGetParams struct {
	// Merchant code.
	Mid string
	// The ID of the transaction event (refund).
	TxEventID *int
}

// QueryValues converts [ReceiptsGetParams] into [url.Values].
func (p *ReceiptsGetParams) QueryValues() url.Values {
	q := make(url.Values)

	q.Set("mid", p.Mid)

	if p.TxEventID != nil {
		q.Set("tx_event_id", strconv.Itoa(*p.TxEventID))
	}

	return q
}

// ReceiptsClient provides access to the Receipts API.
//
// The Receipts model obtains receipt-like details for specific transactions.
type ReceiptsClient struct {
	c *client.Client
}

func NewReceiptsClient(c *client.Client) *ReceiptsClient {
	return &ReceiptsClient{c: c}
}

// Retrieves receipt specific data for a transaction.
func (c *ReceiptsClient) Get(ctx context.Context, id string, params ReceiptsGetParams) (*Receipt, error) {
	path := fmt.Sprintf("/v1.1/receipts/%v", id)

	resp, err := c.c.Call(ctx, http.MethodGet, path, client.WithQueryValues(params.QueryValues()))
	if err != nil {
		return nil, fmt.Errorf("call %s %s: %w", http.MethodGet, path, err)
	}
	defer func() {
		_ = resp.Body.Close()
	}()

	switch resp.StatusCode {
	case http.StatusOK:
		var v Receipt
		if err := json.NewDecoder(resp.Body).Decode(&v); err != nil {
			return nil, fmt.Errorf("decode response: %s", err.Error())
		}

		return &v, nil
	case http.StatusBadRequest:
		var apiErr Error
		if err := json.NewDecoder(resp.Body).Decode(&apiErr); err != nil {
			return nil, fmt.Errorf("read error response: %s", err.Error())
		}

		return nil, &apiErr
	case http.StatusUnauthorized:
		var apiErr Problem
		if err := json.NewDecoder(resp.Body).Decode(&apiErr); err != nil {
			return nil, fmt.Errorf("read error response: %s", err.Error())
		}

		return nil, &apiErr
	case http.StatusNotFound:
		var apiErr Error
		if err := json.NewDecoder(resp.Body).Decode(&apiErr); err != nil {
			return nil, fmt.Errorf("read error response: %s", err.Error())
		}

		return nil, &apiErr
	default:
		return nil, fmt.Errorf("unexpected response %d: %s", resp.StatusCode, http.StatusText(resp.StatusCode))
	}
}
