// Code generated by `gogenitor`. DO NOT EDIT.
package sumup

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"net/http"
)

// SchemasSettingsGet is a schema definition.
type SchemasSettingsGet struct {
	// The part before the @ for the incoming email address for expenses
	// Pattern: ^[\.A-Za-z0-9_-]{8,20}$
	IncomingReceiptEmailUsername *string `json:"incoming_receipt_email_username,omitempty"`
}

// SchemasSettingsUpdate is a schema definition.
type SchemasSettingsUpdate struct {
	// The part before the @ for the incoming email address for expenses
	// Pattern: ^[\.A-Za-z0-9_-]{8,20}$
	IncomingReceiptEmailUsername *string `json:"incoming_receipt_email_username,omitempty"`
}

// UpdateSettingsBody is a schema definition.
type UpdateSettingsBody struct {
	// The part before the @ for the incoming email address for expenses
	// Pattern: ^[\.A-Za-z0-9_-]{8,20}$
	IncomingReceiptEmailUsername *string `json:"incoming_receipt_email_username,omitempty"`
}

var _ error = (*GetSettings4XXResponse)(nil)

// GetSettings4XXResponse: Request validation error
type GetSettings4XXResponse struct {
	Code       *string `json:"code,omitempty"`
	Error      *string `json:"error,omitempty"`
	Message    *string `json:"message,omitempty"`
	StatusCode *int    `json:"status_code,omitempty"`
}

func (e *GetSettings4XXResponse) Error() string {
	return fmt.Sprintf("code=%v, error=%v, message=%v, statusCode=%v", e.Code, e.Error, e.Message, e.StatusCode)
}

var _ error = (*GetSettings5XXResponse)(nil)

// GetSettings5XXResponse: Internal server error
type GetSettings5XXResponse struct {
	Code       *string `json:"code,omitempty"`
	Error      *string `json:"error,omitempty"`
	Message    *string `json:"message,omitempty"`
	StatusCode *int    `json:"status_code,omitempty"`
}

func (e *GetSettings5XXResponse) Error() string {
	return fmt.Sprintf("code=%v, error=%v, message=%v, statusCode=%v", e.Code, e.Error, e.Message, e.StatusCode)
}

var _ error = (*UpdateSettings4XXResponse)(nil)

// UpdateSettings4XXResponse: Request validation error
type UpdateSettings4XXResponse struct {
	Code       *string `json:"code,omitempty"`
	Error      *string `json:"error,omitempty"`
	Message    *string `json:"message,omitempty"`
	StatusCode *int    `json:"status_code,omitempty"`
}

func (e *UpdateSettings4XXResponse) Error() string {
	return fmt.Sprintf("code=%v, error=%v, message=%v, statusCode=%v", e.Code, e.Error, e.Message, e.StatusCode)
}

var _ error = (*UpdateSettings5XXResponse)(nil)

// UpdateSettings5XXResponse: Internal server error
type UpdateSettings5XXResponse struct {
	Code       *string `json:"code,omitempty"`
	Error      *string `json:"error,omitempty"`
	Message    *string `json:"message,omitempty"`
	StatusCode *int    `json:"status_code,omitempty"`
}

func (e *UpdateSettings5XXResponse) Error() string {
	return fmt.Sprintf("code=%v, error=%v, message=%v, statusCode=%v", e.Code, e.Error, e.Message, e.StatusCode)
}

type SettingsService service

// GetSettings: Get merchant settings
func (s *SettingsService) GetSettings(ctx context.Context, merchantCode string) (*SchemasSettingsGet, error) {
	path := fmt.Sprintf("/merchants/%v/expenses-settings", merchantCode)

	req, err := s.client.NewRequest(ctx, http.MethodGet, path, http.NoBody)
	if err != nil {
		return nil, fmt.Errorf("error building request: %v", err)
	}

	resp, err := s.client.Do(req)
	if err != nil {
		return nil, fmt.Errorf("error sending request: %v", err)
	}
	defer resp.Body.Close()

	switch resp.StatusCode {
	case http.StatusOK:
		var v SchemasSettingsGet
		if err := json.NewDecoder(resp.Body).Decode(&v); err != nil {
			return nil, fmt.Errorf("decode response: %s", err.Error())
		}

		return &v, nil
	case http.StatusBadRequest:
		var apiErr GetSettings4XXResponse
		if err := json.NewDecoder(resp.Body).Decode(&apiErr); err != nil {
			return nil, fmt.Errorf("read error response: %s", err.Error())
		}

		return nil, &apiErr
	case http.StatusInternalServerError:
		var apiErr GetSettings5XXResponse
		if err := json.NewDecoder(resp.Body).Decode(&apiErr); err != nil {
			return nil, fmt.Errorf("read error response: %s", err.Error())
		}

		return nil, &apiErr
	default:
		return nil, fmt.Errorf("unexpected response %d: %s", resp.StatusCode, http.StatusText(resp.StatusCode))
	}
}

// UpdateSettings: Update merchant settings
func (s *SettingsService) UpdateSettings(ctx context.Context, merchantCode string, body UpdateSettingsBody) (*SchemasSettingsGet, error) {
	buf := new(bytes.Buffer)
	if err := json.NewEncoder(buf).Encode(body); err != nil {
		return nil, fmt.Errorf("encoding json body request failed: %v", err)
	}

	path := fmt.Sprintf("/merchants/%v/expenses-settings", merchantCode)

	req, err := s.client.NewRequest(ctx, http.MethodPut, path, buf)
	if err != nil {
		return nil, fmt.Errorf("error building request: %v", err)
	}

	resp, err := s.client.Do(req)
	if err != nil {
		return nil, fmt.Errorf("error sending request: %v", err)
	}
	defer resp.Body.Close()

	switch resp.StatusCode {
	case http.StatusOK:
		var v SchemasSettingsGet
		if err := json.NewDecoder(resp.Body).Decode(&v); err != nil {
			return nil, fmt.Errorf("decode response: %s", err.Error())
		}

		return &v, nil
	case http.StatusBadRequest:
		var apiErr UpdateSettings4XXResponse
		if err := json.NewDecoder(resp.Body).Decode(&apiErr); err != nil {
			return nil, fmt.Errorf("read error response: %s", err.Error())
		}

		return nil, &apiErr
	case http.StatusInternalServerError:
		var apiErr UpdateSettings5XXResponse
		if err := json.NewDecoder(resp.Body).Decode(&apiErr); err != nil {
			return nil, fmt.Errorf("read error response: %s", err.Error())
		}

		return nil, &apiErr
	default:
		return nil, fmt.Errorf("unexpected response %d: %s", resp.StatusCode, http.StatusText(resp.StatusCode))
	}
}
