// Code generated by `go-sdk-gen`. DO NOT EDIT.

package subaccounts

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"strconv"
	"time"

	"github.com/sumup/sumup-go/client"
	"github.com/sumup/sumup-go/shared"
)

// CompatError: Error
type CompatError struct {
	ErrorCode string `json:"error_code"`
	Message   string `json:"message"`
}

func (e *CompatError) Error() string {
	return fmt.Sprintf("error_code=%v, message=%v", e.ErrorCode, e.Message)
}

var _ error = (*CompatError)(nil)

// Operator is a schema definition.
type Operator struct {
	AccountType OperatorAccountType `json:"account_type"`
	// The timestamp of when the operator was created.
	CreatedAt time.Time `json:"created_at"`
	Disabled  bool      `json:"disabled"`
	// Format: int32
	Id       int     `json:"id"`
	Nickname *string `json:"nickname,omitempty"`
	// User permissions
	Permissions shared.Permissions `json:"permissions"`
	// The timestamp of when the operator was last updated.
	UpdatedAt time.Time `json:"updated_at"`
	Username  string    `json:"username"`
}

// OperatorAccountType is a schema definition.
type OperatorAccountType string

const (
	OperatorAccountTypeNormal   OperatorAccountType = "normal"
	OperatorAccountTypeOperator OperatorAccountType = "operator"
)

// CreateSubAccountBody is a schema definition.
type CreateSubAccountBody struct {
	Nickname *string `json:"nickname,omitempty"`
	// Min length: 8
	Password    string                           `json:"password"`
	Permissions *CreateSubAccountBodyPermissions `json:"permissions,omitempty"`
	// Format: email
	Username string `json:"username"`
}

// CreateSubAccountBodyPermissions is a schema definition.
type CreateSubAccountBodyPermissions struct {
	CreateMotoPayments         *bool `json:"create_moto_payments,omitempty"`
	CreateReferral             *bool `json:"create_referral,omitempty"`
	FullTransactionHistoryView *bool `json:"full_transaction_history_view,omitempty"`
	RefundTransactions         *bool `json:"refund_transactions,omitempty"`
}

// CompatChangeOperatorsPasswordBody is a schema definition.
type CompatChangeOperatorsPasswordBody struct {
	// Min length: 8
	Password *string `json:"password,omitempty"`
}

// UpdateSubAccountBody is a schema definition.
type UpdateSubAccountBody struct {
	Disabled *bool   `json:"disabled,omitempty"`
	Nickname *string `json:"nickname,omitempty"`
	// Min length: 8
	Password    *string                          `json:"password,omitempty"`
	Permissions *UpdateSubAccountBodyPermissions `json:"permissions,omitempty"`
	// Format: email
	// Max length: 256
	Username *string `json:"username,omitempty"`
}

// UpdateSubAccountBodyPermissions is a schema definition.
type UpdateSubAccountBodyPermissions struct {
	CreateMotoPayments         *bool `json:"create_moto_payments,omitempty"`
	CreateReferral             *bool `json:"create_referral,omitempty"`
	FullTransactionHistoryView *bool `json:"full_transaction_history_view,omitempty"`
	RefundTransactions         *bool `json:"refund_transactions,omitempty"`
}

// ListSubAccountsParams: query parameters for ListSubAccounts
type ListSubAccountsParams struct {
	// If true the list of operators will include also the primary user.
	IncludePrimary *bool
	// Search query used to filter users that match given query term.
	//
	// Current implementation allow querying only over the email address.
	// All operators whos email address contains the query string are returned.
	Query *string
}

// QueryValues converts [ListSubAccountsParams] into [url.Values].
func (p *ListSubAccountsParams) QueryValues() url.Values {
	q := make(url.Values)

	if p.IncludePrimary != nil {
		q.Set("include_primary", strconv.FormatBool(*p.IncludePrimary))
	}

	if p.Query != nil {
		q.Set("query", *p.Query)
	}

	return q
}

// ListSubAccounts200Response is a schema definition.
type ListSubAccounts200Response []Operator

type SubaccountsService struct {
	c *client.Client
}

func NewSubaccountsService(c *client.Client) *SubaccountsService {
	return &SubaccountsService{c: c}
}

// ListSubAccounts: List operators.
// Returns list of operators for currently authorized user's merchant.
// Deprecated: Subaccounts API is deprecated, to list users in your merchant account please use [List members](https://developer.sumup.com/api/members/list) instead.
func (s *SubaccountsService) ListSubAccounts(ctx context.Context, params ListSubAccountsParams) (*ListSubAccounts200Response, error) {
	path := fmt.Sprintf("/v0.1/me/accounts")

	resp, err := s.c.Call(ctx, http.MethodGet, path, client.WithQueryValues(params.QueryValues()))
	if err != nil {
		return nil, fmt.Errorf("error building request: %v", err)
	}
	defer resp.Body.Close()

	switch resp.StatusCode {
	case http.StatusOK:
		var v ListSubAccounts200Response
		if err := json.NewDecoder(resp.Body).Decode(&v); err != nil {
			return nil, fmt.Errorf("decode response: %s", err.Error())
		}

		return &v, nil
	default:
		return nil, fmt.Errorf("unexpected response %d: %s", resp.StatusCode, http.StatusText(resp.StatusCode))
	}
}

// CreateSubAccount: Create operator.
// Creates new operator for currently authorized users' merchant.
// Deprecated: Subaccounts API is deprecated, to create an user in your merchant account please use [Create member](https://developer.sumup.com/api/members/create)
// instead.
func (s *SubaccountsService) CreateSubAccount(ctx context.Context, body CreateSubAccountBody) (*Operator, error) {
	path := fmt.Sprintf("/v0.1/me/accounts")

	resp, err := s.c.Call(ctx, http.MethodPost, path, client.WithJSONBody(body))
	if err != nil {
		return nil, fmt.Errorf("error building request: %v", err)
	}
	defer resp.Body.Close()

	switch resp.StatusCode {
	case http.StatusOK:
		var v Operator
		if err := json.NewDecoder(resp.Body).Decode(&v); err != nil {
			return nil, fmt.Errorf("decode response: %s", err.Error())
		}

		return &v, nil
	case http.StatusForbidden:
		var apiErr CompatError
		if err := json.NewDecoder(resp.Body).Decode(&apiErr); err != nil {
			return nil, fmt.Errorf("read error response: %s", err.Error())
		}

		return nil, &apiErr
	default:
		return nil, fmt.Errorf("unexpected response %d: %s", resp.StatusCode, http.StatusText(resp.StatusCode))
	}
}

// CompatChangeOperatorsPassword: Change operators password.
// Changes operators password, if the operator was disabled they will be unblocked.
// Deprecated: Subaccounts API is deprecated, to update an user that's a member of your merchant account please
// use [Update member](https://developer.sumup.com/api/members/update) instead.
func (s *SubaccountsService) CompatChangeOperatorsPassword(ctx context.Context, operatorId int, body CompatChangeOperatorsPasswordBody) (*Operator, error) {
	path := fmt.Sprintf("/v0.1/me/accounts/%v/reset", operatorId)

	resp, err := s.c.Call(ctx, http.MethodPut, path, client.WithJSONBody(body))
	if err != nil {
		return nil, fmt.Errorf("error building request: %v", err)
	}
	defer resp.Body.Close()

	switch resp.StatusCode {
	case http.StatusOK:
		var v Operator
		if err := json.NewDecoder(resp.Body).Decode(&v); err != nil {
			return nil, fmt.Errorf("decode response: %s", err.Error())
		}

		return &v, nil
	case http.StatusBadRequest:
		var apiErr CompatError
		if err := json.NewDecoder(resp.Body).Decode(&apiErr); err != nil {
			return nil, fmt.Errorf("read error response: %s", err.Error())
		}

		return nil, &apiErr
	default:
		return nil, fmt.Errorf("unexpected response %d: %s", resp.StatusCode, http.StatusText(resp.StatusCode))
	}
}

// CompatDisableOperator: Disable operator.
//
// Deprecated: Subaccounts API is deprecated, to remove an user that's a member of your merchant account please
// use [Delete member](https://developer.sumup.com/api/members/delete) instead.
func (s *SubaccountsService) CompatDisableOperator(ctx context.Context, operatorId int) (*Operator, error) {
	path := fmt.Sprintf("/v0.1/me/accounts/%v/disable", operatorId)

	resp, err := s.c.Call(ctx, http.MethodPost, path)
	if err != nil {
		return nil, fmt.Errorf("error building request: %v", err)
	}
	defer resp.Body.Close()

	switch resp.StatusCode {
	case http.StatusOK:
		var v Operator
		if err := json.NewDecoder(resp.Body).Decode(&v); err != nil {
			return nil, fmt.Errorf("decode response: %s", err.Error())
		}

		return &v, nil
	default:
		return nil, fmt.Errorf("unexpected response %d: %s", resp.StatusCode, http.StatusText(resp.StatusCode))
	}
}

// DeactivateSubAccount: Disable operator.
//
// Deprecated: Subaccounts API is deprecated, to remove an user that's a member of your merchant account please
// use [Delete member](https://developer.sumup.com/api/members/delete) instead.
func (s *SubaccountsService) DeactivateSubAccount(ctx context.Context, operatorId int) (*Operator, error) {
	path := fmt.Sprintf("/v0.1/me/accounts/%v", operatorId)

	resp, err := s.c.Call(ctx, http.MethodDelete, path)
	if err != nil {
		return nil, fmt.Errorf("error building request: %v", err)
	}
	defer resp.Body.Close()

	switch resp.StatusCode {
	case http.StatusOK:
		var v Operator
		if err := json.NewDecoder(resp.Body).Decode(&v); err != nil {
			return nil, fmt.Errorf("decode response: %s", err.Error())
		}

		return &v, nil
	default:
		return nil, fmt.Errorf("unexpected response %d: %s", resp.StatusCode, http.StatusText(resp.StatusCode))
	}
}

// CompatGetOperator: Get operator
// Returns specific operator.
// Deprecated: Subaccounts API is deprecated, to get an user that's a member of your merchant account please use
// [Get member](https://developer.sumup.com/api/members/get) instead.
func (s *SubaccountsService) CompatGetOperator(ctx context.Context, operatorId int) (*Operator, error) {
	path := fmt.Sprintf("/v0.1/me/accounts/%v", operatorId)

	resp, err := s.c.Call(ctx, http.MethodGet, path)
	if err != nil {
		return nil, fmt.Errorf("error building request: %v", err)
	}
	defer resp.Body.Close()

	switch resp.StatusCode {
	case http.StatusOK:
		var v Operator
		if err := json.NewDecoder(resp.Body).Decode(&v); err != nil {
			return nil, fmt.Errorf("decode response: %s", err.Error())
		}

		return &v, nil
	default:
		return nil, fmt.Errorf("unexpected response %d: %s", resp.StatusCode, http.StatusText(resp.StatusCode))
	}
}

// UpdateSubAccount: Update operator.
// Updates operator. If the operator was disabled and their password is updated they will be unblocked.
// Deprecated: Subaccounts API is deprecated, to update an user that's a member of your merchant account please
// use [Update member](https://developer.sumup.com/api/members/update) instead.
func (s *SubaccountsService) UpdateSubAccount(ctx context.Context, operatorId int, body UpdateSubAccountBody) (*Operator, error) {
	path := fmt.Sprintf("/v0.1/me/accounts/%v", operatorId)

	resp, err := s.c.Call(ctx, http.MethodPut, path, client.WithJSONBody(body))
	if err != nil {
		return nil, fmt.Errorf("error building request: %v", err)
	}
	defer resp.Body.Close()

	switch resp.StatusCode {
	case http.StatusOK:
		var v Operator
		if err := json.NewDecoder(resp.Body).Decode(&v); err != nil {
			return nil, fmt.Errorf("decode response: %s", err.Error())
		}

		return &v, nil
	case http.StatusBadRequest:
		var apiErr CompatError
		if err := json.NewDecoder(resp.Body).Decode(&apiErr); err != nil {
			return nil, fmt.Errorf("read error response: %s", err.Error())
		}

		return nil, &apiErr
	default:
		return nil, fmt.Errorf("unexpected response %d: %s", resp.StatusCode, http.StatusText(resp.StatusCode))
	}
}
