version: "2"
linters:
  default: standard
issues:
  max-same-issues: 0
  max-issues-per-linter: 0
  uniq-by-line: true
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/sumup/go-sdk-gen)
        - dot
    gofmt:
      simplify: true
    goimports:
      local-prefixes:
        - github.com/sumup/go-sdk-gen
  exclusions:
    generated: lax
