// Code generated by `go-sdk-gen`. DO NOT EDIT.

package nullable

import (
	"encoding/json"
	"fmt"
)

var _ json.Marshaler = (*Field[string])(nil)
var _ json.Unmarshaler = (*Field[string])(nil)

// Field is a wrapper for nullable fields to distinguish zero values
// from null or omitted fields.
type Field[T any] struct {
	Value   T
	Null    bool
	Present bool
}

func (f Field[T]) IsZero() bool {
	return !f.Present
}

func (f Field[T]) MarshalJSON() ([]byte, error) {
	if f.Null {
		return []byte("null"), nil // Explicitly set to null
	}
	return json.Marshal(f.Value)
}

func (f *Field[T]) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		f.Null = true
		f.Present = true
		var zeroValue T
		f.Value = zeroValue // Reset value
		return nil
	}
	f.Present = true
	return json.Unmarshal(data, &f.Value)
}

func (f Field[T]) String() string {
	return fmt.Sprintf("%v", f.Value)
}

// Value is a nullable field helper for constructing a generic nullable field
// with a value.
func Value[T any](value T) Field[T] { return Field[T]{Value: value, Present: true} }

// Null is a nullable field helper for constructing a generic null fields.
func Null[T any]() Field[T] { return Field[T]{Null: true, Present: true} }

// Int is a nullable field helper for constructing nullable integers with a value.
func Int(value int) Field[int] { return Value(value) }

// Int32 is a nullable field helper for constructing nullable int32 values.
func Int32(value int32) Field[int32] { return Value(value) }

// Int64 is a nullable field helper for constructing nullable int64 values.
func Int64(value int64) Field[int64] { return Value(value) }

// String is a nullable field helper for constructing nullable strings with a value.
func String(value string) Field[string] { return Value(value) }

// Float is a nullable field helper for constructing nullable floats with a value.
func Float(value float32) Field[float32] { return Value(value) }

// Float64 is a nullable field helper for constructing nullable float64 values.
func Float64(value float64) Field[float64] { return Value(value) }

// Bool is a nullable field helper for constructing nullable bools with a value.
func Bool(value bool) Field[bool] { return Value(value) }
