name: Github Actions

on:
  pull_request:
    paths:
      - '.github/**'

defaults:
  run:
    working-directory: ./.github

permissions:
  contents: read

jobs:
  actionlint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
          sparse-checkout: |
            .github

      - uses: reviewdog/action-actionlint@50842263c20a7c46bd0065b9e624d3c569db061e # v1.73.0
        with:
          filter_mode: nofilter
          fail_on_error: true
          reporter: github-pr-check
