on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  notify:
    name: Notify
    runs-on: ubuntu-latest
    steps:
      - name: Send release notification
        uses: slackapi/slack-github-action@b0fa283ad8fea605de13dc3f449259339835fc52 # v2.1.0
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: webhook-trigger
          payload: |
            repo: "${{ github.repository }}"
            url: "${{ github.event.release.html_url }}"
            version: "${{ github.event.release.tag_name }}"
